// Rich, per-product detail shown when a client opens a purchased item card.
// Keyed by productId (matches create-checkout's server catalog + seeded purchases).
import {
  Palette, Globe, Sparkles, Crown, Rocket, Smartphone, Wallet,
} from "lucide-react";

export const PRODUCT_DETAILS = {
  branding: {
    icon: Palette,
    accent: "from-fuchsia-500/20 to-lime-400/10",
    tagline: "Complete brand identity, generated by AI",
    description:
      "A full brand kit built from your business name and industry — positioning, logo, business card, brochure, social posts, and a short brand video. Everything you need to look established from day one.",
    features: [
      "Brand strategy: positioning, promise, tagline & voice",
      "Primary logo + alternate lockups",
      "Business card (front & back)",
      "Tri-fold brochure with copy",
      "Social post set (image + caption per platform)",
      "Short brand video",
    ],
    deliverables: ["Logo files (PNG + SVG)", "Brand color palette", "Typography pairing", "Ready-to-post social assets"],
  },
  "web-pack": {
    icon: Globe,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "A conversion-ready website, built and deployed",
    description:
      "A complete epoxy contractor website package — custom logo, brand mockups, a built-to-order website, and full SEO/AEO optimization — deployed to a live URL ready to rank and capture leads.",
    features: [
      "Logo Generator — 10 custom logo concepts built from your business name, you pick 1",
      "Brand Generator — 10 real-world brand mockups using your logo, you pick up to 3:",
      "  · Business cards (front & back)",
      "  · Tri-fold brochure",
      "  · Digital marketing flyer",
      "  · Branded t-shirt",
      "  · Embroidered hat / cap",
      "  · Mobile app mockup",
      "  · Vehicle / van wrap",
      "  · Storefront signage",
      "  · Social media kit",
      "  · Branded work uniform",
      "Website Design — 10 web design packs with desktop & mobile preview + color toggle, you pick up to 3",
      "Website Build — custom design from your chosen direction",
      "Hero, About, Services & FAQ copy written for your epoxy business",
      "AI-generated project imagery",
      "Mobile-responsive design (phone, tablet & desktop)",
      "On-page SEO optimization",
      "AI-search (AEO) answer optimization",
      "JSON-LD structured data",
      "Lead capture form wiring",
      "Domain selection",
      "Hosting & deployment to a live URL",
      "Launch & go-live",
    ],
    deliverables: ["Live website URL", "Chosen logo files", "Chosen brand mockups", "SEO-optimized pages", "Mobile-responsive design", "Lead capture wiring"],
  },
  "ai-tool": {
    icon: Sparkles,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Autonomous AI tool credit",
    description:
      "An à-la-carte AI tool credit — rank engine, content generator, citation builder, or backlink outreach. Each tool runs autonomously and reports back through your portal.",
    features: [
      "Choose any active AI tool in the system",
      "Autonomous execution with receipts",
      "Results tracked in your portal",
      "Re-runnable as often as you need",
    ],
    deliverables: ["Tool run receipt", "Output assets / report", "Progress tracked in portal"],
  },
  "app-pack": {
    icon: Smartphone,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Native iOS & Android app build",
    description:
      "We package your site/brand into a native mobile app and ship it to the App Store and Google Play from the same codebase.",
    features: [
      "Native iOS build",
      "Native Android build",
      "App Store submission",
      "Google Play submission",
      "Push notification setup",
    ],
    deliverables: ["Published app listings", "Push credential config", "App binaries"],
  },
  deposit: {
    icon: Wallet,
    accent: "from-amber-500/20 to-lime-400/10",
    tagline: "Done-for-you service deposit",
    description:
      "A deposit that locks in a done-for-you engagement. Applied toward your total once the scope is finalized.",
    features: [
      "Discovery & scoping call",
      "Custom build plan",
      "Deposit credited to final invoice",
    ],
    deliverables: ["Signed scope", "Build plan", "Credited deposit"],
  },
  "pro-monthly": { icon: Rocket, accent: "from-lime-400/20 to-emerald-400/10", tagline: "Pro plan — monthly subscription", description: "The Pro plan, billed monthly. Full access to the growth factory for one market.", features: ["1 market/site", "Rank engine + citations", "GSC sync", "Backlink outreach"], deliverables: ["Monthly execution", "Portal access"] },
  "pro-annual": { icon: Rocket, accent: "from-lime-400/20 to-emerald-400/10", tagline: "Pro plan — annual subscription", description: "The Pro plan, billed annually at a discount.", features: ["1 market/site", "Rank engine + citations", "GSC sync", "Backlink outreach"], deliverables: ["Annual execution", "Portal access"] },
  "elite-monthly": { icon: Crown, accent: "from-amber-400/20 to-fuchsia-400/10", tagline: "Elite plan — monthly subscription", description: "The Elite plan, billed monthly. Multi-market scale with priority execution.", features: ["Multiple markets", "Priority execution", "Dedicated support", "All tools unlocked"], deliverables: ["Monthly execution", "Priority portal"] },
  "elite-annual": { icon: Crown, accent: "from-amber-400/20 to-fuchsia-400/10", tagline: "Elite plan — annual subscription", description: "The Elite plan, billed annually at a discount.", features: ["Multiple markets", "Priority execution", "Dedicated support", "All tools unlocked"], deliverables: ["Annual execution", "Priority portal"] },
};

export function getProductDetails(productId) {
  return PRODUCT_DETAILS[productId] || {
    icon: Sparkles,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Purchased product",
    description: "This item is part of your package. Open a support request for full details.",
    features: [],
    deliverables: [],
  };
}