// Complete catalog of all services, plans, and à-la-carte tools offered.
// Used by the Pricing page, admin gallery, and checkout flow. Each entry
// has detailed features, statistics, delivery time, and contract terms so
// the client can review exactly what they're buying before they pay.

import {
  Crown, Rocket, Sparkles, Globe, Smartphone, Wallet, Bot, Palette,
  Search, FileText, Megaphone, BarChart3, Phone, Zap, MapPin, Star,
} from "lucide-react";

export const SERVICE_CATALOG = [
  // ─── PLANS ───────────────────────────────────────────────
  {
    id: "elite-monthly",
    name: "Elite Plan — Monthly",
    price: 1499,
    priceLabel: "$1,499/mo",
    category: "plan",
    icon: Crown,
    accent: "from-amber-400/20 to-fuchsia-400/10",
    tagline: "Done-for-you growth engine across multiple markets",
    description: "The complete epoxy contractor growth package — 100% digital deliverables. Custom digital logo, full digital brand identity, a built-to-order conversion website, SEO/AEO optimization, rank engine, citations, backlinks and ongoing reporting.",
    features: [
      "Multiple markets / sites included",
      "Priority execution (jump the queue)",
      "Dedicated support & project lead",
      "Logo Generator — 10 concepts per market, pick 1",
      "Brand Generator — 10 mockups per market, pick up to 3",
      "Website Design — 10 packs per market, pick up to 3",
      "Website build per market (design, copy, imagery)",
      "On-page SEO + AEO optimization per site",
      "JSON-LD structured data per site",
      "Rank Engine — pages, citations & backlinks per market",
      "GSC sync, indexing & traffic tracking",
      "Ongoing content refresh & optimization",
      "Lead capture wiring per site",
      "Monthly execution & priority reporting",
      "All tools unlocked",
    ],
    statistics: [
      { label: "Avg. lead increase", value: "3.2×" },
      { label: "Time to page one", value: "60–90 days" },
      { label: "Markets included", value: "Multiple" },
      { label: "Iterations included", value: "2 free" },
    ],
    deliveryTime: "7 days",
    productId: "elite-monthly",
  },
  {
    id: "elite-annual",
    name: "Elite Plan — Annual",
    price: 14990,
    priceLabel: "$1,499/mo (billed annually)",
    category: "plan",
    icon: Crown,
    accent: "from-amber-400/20 to-fuchsia-400/10",
    tagline: "Elite plan billed annually — save 2 months",
    description: "Same Elite growth engine, billed annually at a discount. Full-service brand, web, sites, ranking, citations, backlinks & reporting with priority execution across multiple markets.",
    features: [
      "Everything in Elite Monthly",
      "Annual billing discount (save 2 months)",
      "Annual execution & monthly priority reporting",
    ],
    statistics: [
      { label: "Savings vs monthly", value: "$2,998/yr" },
      { label: "Avg. lead increase", value: "3.2×" },
      { label: "Time to page one", value: "60–90 days" },
    ],
    deliveryTime: "7 days",
    productId: "elite-annual",
  },
  {
    id: "pro-monthly",
    name: "Pro Plan — Monthly",
    price: 499,
    priceLabel: "$499/mo",
    category: "plan",
    icon: Rocket,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Full-service brand, website & ranking for one market",
    description: "Everything you need to launch and grow a single local site — brand kit, website build, SEO/AEO, rank engine, and monthly reporting.",
    features: [
      "1 market / site included",
      "Onboarding & business profile intake",
      "Logo Generator — 10 concepts, pick 1",
      "Brand Generator — 10 mockups, pick up to 3",
      "Website Design — 10 packs, pick up to 3",
      "Website build (design, copy, imagery)",
      "On-page SEO + AEO optimization",
      "JSON-LD structured data",
      "Rank Engine — SEO pages, citations & backlinks",
      "GSC sync & indexing",
      "Backlink outreach",
      "Lead capture wiring",
      "Monthly execution & reporting",
      "Portal access",
    ],
    statistics: [
      { label: "Avg. lead increase", value: "2.1×" },
      { label: "Time to page one", value: "90–120 days" },
      { label: "Markets included", value: "1" },
      { label: "Iterations included", value: "2 free" },
    ],
    deliveryTime: "7 days",
    productId: "pro-monthly",
  },
  {
    id: "pro-annual",
    name: "Pro Plan — Annual",
    price: 4990,
    priceLabel: "$416/mo (billed annually)",
    category: "plan",
    icon: Rocket,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Pro plan billed annually — save 2 months",
    description: "Same Pro plan, billed annually at a discount. Full-service brand, website & ranking engine for one market.",
    features: [
      "Everything in Pro Monthly",
      "Annual billing discount (save 2 months)",
    ],
    statistics: [
      { label: "Savings vs monthly", value: "$998/yr" },
      { label: "Avg. lead increase", value: "2.1×" },
      { label: "Time to page one", value: "90–120 days" },
    ],
    deliveryTime: "7 days",
    productId: "pro-annual",
  },

  // ─── À LA CARTE — PACKAGES ───────────────────────────────
  {
    id: "web-pack",
    name: "Web Pack",
    price: 299,
    priceLabel: "From $299",
    category: "package",
    icon: Globe,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "A conversion-ready website, built and deployed",
    description: "A complete epoxy contractor website package — custom logo, brand mockups, a built-to-order website, and full SEO/AEO optimization — deployed to a live URL ready to rank and capture leads.",
    features: [
      "Logo Generator — 10 custom logo concepts, pick 1",
      "Brand Generator — 10 brand mockups, pick up to 3",
      "Website Design — 10 web design packs, pick up to 3",
      "Website Build — custom design from your chosen direction",
      "Hero, About, Services & FAQ copy written for your business",
      "AI-generated project imagery",
      "Mobile-responsive design (phone, tablet & desktop)",
      "On-page SEO optimization",
      "AI-search (AEO) answer optimization",
      "JSON-LD structured data",
      "Lead capture form wiring",
      "Domain selection",
      "Hosting & deployment to a live URL",
      "Launch & go-live",
    ],
    statistics: [
      { label: "Pages built", value: "5–10" },
      { label: "Design concepts", value: "10" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "web-pack",
  },
  {
    id: "app-pack",
    name: "App Pack",
    price: 499,
    priceLabel: "From $499",
    category: "package",
    icon: Smartphone,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Native iOS & Android app build from your site",
    description: "We package your site/brand into a native mobile app and ship it to the App Store and Google Play from the same codebase.",
    features: [
      "Brand kit (logo, colors, typography)",
      "Website build (design, copy & deploy)",
      "Native iOS app build",
      "Native Android app build",
      "App Store submission & listing",
      "Google Play submission & listing",
      "Push notification setup",
      "App icons & splash screens",
      "In-app lead capture",
    ],
    statistics: [
      { label: "Platforms", value: "iOS + Android" },
      { label: "Delivery", value: "7 days" },
      { label: "App stores", value: "2" },
    ],
    deliveryTime: "7 days",
    productId: "app-pack",
  },
  {
    id: "deposit",
    name: "Done-For-You Service Deposit",
    price: 500,
    priceLabel: "$500 deposit",
    category: "package",
    icon: Wallet,
    accent: "from-amber-500/20 to-lime-400/10",
    tagline: "Lock in a done-for-you engagement",
    description: "A deposit that locks in a done-for-you engagement. Applied toward your total once the scope is finalized.",
    features: [
      "Discovery & scoping call",
      "Business profile intake",
      "Custom build plan",
      "Itemized scope of work",
      "Signed agreement",
      "Deposit credited to final invoice",
      "Dedicated project lead assigned",
    ],
    statistics: [
      { label: "Applied to total", value: "100%" },
      { label: "Discovery call", value: "15 min" },
    ],
    deliveryTime: "7 days",
    productId: "deposit",
  },

  // ─── À LA CARTE — AI TOOLS ───────────────────────────────
  {
    id: "ai-tool-rank-engine",
    name: "Rank Engine",
    price: 99,
    priceLabel: "$99/run",
    category: "ai-tool",
    icon: Search,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Generate & deploy SEO pages automatically",
    description: "An autonomous SEO page generator that creates city-service pages, deploys them, and tracks rankings. Each run produces optimized pages targeting your local keywords.",
    features: [
      "AI-generated city-service pages",
      "Keyword research & targeting",
      "On-page SEO optimization",
      "JSON-LD structured data",
      "Automatic deployment",
      "Ranking tracking",
      "Run receipt & report",
    ],
    statistics: [
      { label: "Pages per run", value: "10–50" },
      { label: "Avg. ranking lift", value: "+15 positions" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool",
  },
  {
    id: "ai-tool-citation",
    name: "Citation Builder",
    price: 99,
    priceLabel: "$99/run",
    category: "ai-tool",
    icon: MapPin,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Submit your business to local directories",
    description: "Automatically submits your business to local citation directories (Yelp, BBB, Angi, etc.) to boost local search visibility and build authority.",
    features: [
      "50+ directory submissions",
      "NAP consistency check",
      "Tier 1 & tier 2 directories",
      "Submission tracking",
      "Live link verification",
      "Run receipt & report",
    ],
    statistics: [
      { label: "Directories per run", value: "50+" },
      { label: "Avg. DA boost", value: "+8 points" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool",
  },
  {
    id: "ai-tool-backlink",
    name: "Backlink Outreach",
    price: 99,
    priceLabel: "$99/run",
    category: "ai-tool",
    icon: Megaphone,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Find & contact backlink prospects automatically",
    description: "Finds relevant backlink prospects in your niche, drafts personalized outreach emails, and tracks responses to build authority.",
    features: [
      "Prospect discovery (50+ per run)",
      "Personalized email drafting",
      "Relevance & DA scoring",
      "Outreach tracking",
      "Follow-up automation",
      "Run receipt & report",
    ],
    statistics: [
      { label: "Prospects per run", value: "50+" },
      { label: "Avg. response rate", value: "8–12%" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool",
  },
  {
    id: "ai-tool-content",
    name: "Content Generator",
    price: 99,
    priceLabel: "$99/run",
    category: "ai-tool",
    icon: FileText,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Refresh & expand your site copy with AI",
    description: "Generates fresh, SEO-optimized content for your website — blog articles, service pages, FAQs, and location pages tailored to your niche.",
    features: [
      "Blog article generation",
      "Service page copy",
      "FAQ generation",
      "Location page copy",
      "SEO keyword integration",
      "Run receipt & report",
    ],
    statistics: [
      { label: "Articles per run", value: "10" },
      { label: "Avg. word count", value: "1,200+" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool",
  },
  {
    id: "ai-tool-brand",
    name: "AI Brand Designer",
    price: 99,
    priceLabel: "$99/run",
    category: "ai-tool",
    icon: Palette,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Generate a complete brand kit with AI",
    description: "Creates a full brand identity — positioning, logo concepts, color palette, typography, and brand voice — from your business name and industry.",
    features: [
      "10 logo concepts",
      "Color palette generation",
      "Typography pairing",
      "Brand voice & positioning",
      "Tagline suggestions",
      "Run receipt & files",
    ],
    statistics: [
      { label: "Logo concepts", value: "10" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool",
  },
  {
    id: "ai-tool-chatbot",
    name: "AI Lead Chatbot",
    price: 99,
    priceLabel: "$99/setup",
    category: "ai-tool",
    icon: Bot,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "24/7 AI chatbot that captures & qualifies leads",
    description: "An AI-powered chatbot for your website that answers visitor questions, qualifies leads, and books appointments — even when you're asleep.",
    features: [
      "AI-powered lead qualification",
      "Appointment booking",
      "FAQ answering",
      "Lead capture & routing",
      "CRM integration",
      "Setup receipt & config",
    ],
    statistics: [
      { label: "Lead capture rate", value: "+40%" },
      { label: "24/7 availability", value: "Always on" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool",
  },

  // ─── À LA CARTE — INDIVIDUAL SERVICES ────────────────────
  {
    id: "service-seo-audit",
    name: "SEO Audit",
    price: 149,
    priceLabel: "$149",
    category: "service",
    icon: BarChart3,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "Full technical & content SEO audit",
    description: "A comprehensive SEO audit of your existing website — technical issues, content gaps, ranking opportunities, and a prioritized action plan.",
    features: [
      "Technical SEO audit",
      "Content gap analysis",
      "Keyword opportunity report",
      "Competitor analysis",
      "Prioritized action plan",
      "PDF report",
    ],
    statistics: [
      { label: "Checks performed", value: "50+" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "ai-tool",
  },
  {
    id: "service-gbp-setup",
    name: "Google Business Profile Setup",
    price: 300,
    priceLabel: "$300",
    category: "service",
    icon: MapPin,
    accent: "from-amber-500/20 to-lime-400/10",
    tagline: "Complete GBP setup & optimization",
    description: "Complete setup and optimization of your Google Business Profile for maximum local search visibility.",
    features: [
      "Profile creation & verification",
      "Category optimization",
      "Service area setup",
      "Photo upload & optimization",
      "Review request system",
      "Q&A setup",
    ],
    statistics: [
      { label: "Local pack visibility", value: "+60%" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "ai-tool",
  },
  {
    id: "service-call-tracking",
    name: "Call Tracking Number",
    price: 200,
    priceLabel: "$200",
    category: "service",
    icon: Phone,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Dedicated tracking number with analytics",
    description: "Dedicated tracking phone number with call recording and analytics to measure your lead flow.",
    features: [
      "Dedicated tracking number",
      "Call recording",
      "Call analytics dashboard",
      "Lead source attribution",
      "SMS notifications",
    ],
    statistics: [
      { label: "Call tracking", value: "100%" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool",
  },
  {
    id: "service-rush",
    name: "Priority Rush Delivery",
    price: 500,
    priceLabel: "$500",
    category: "service",
    icon: Zap,
    accent: "from-amber-400/20 to-fuchsia-400/10",
    tagline: "Get your project delivered in 3 business days",
    description: "Jump the queue and get your website built and launched in 3 business days instead of the standard 7-day timeline.",
    features: [
      "3 business day delivery",
      "Priority queue position",
      "Dedicated builder",
      "Expedited review cycles",
    ],
    statistics: [
      { label: "Delivery", value: "3 days" },
      { label: "Priority", value: "Highest" },
    ],
    deliveryTime: "3 days",
    productId: "ai-tool",
  },
  {
    id: "service-reviews",
    name: "Review Management System",
    price: 400,
    priceLabel: "$400",
    category: "service",
    icon: Star,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Automated review request system",
    description: "Automated review request system that sends review links to your customers after job completion, boosting your Google rating.",
    features: [
      "Automated review requests",
      "SMS + email delivery",
      "Review tracking dashboard",
      "Negative review alerts",
      "Response templates",
    ],
    statistics: [
      { label: "Review rate", value: "+35%" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool",
  },
];

export const CATEGORIES = [
  { id: "plan", label: "Subscription Plans", icon: Crown },
  { id: "package", label: "Packages", icon: Globe },
  { id: "ai-tool", label: "AI Tools", icon: Bot },
  { id: "service", label: "Individual Services", icon: Sparkles },
];

export function getServicesByCategory(cat) {
  return SERVICE_CATALOG.filter((s) => s.category === cat);
}