// Complete catalog of all services, plans, and à-la-carte tools offered.
// Used by the Pricing page, admin gallery, and checkout flow. Each entry
// has detailed features, statistics, delivery time, and contract terms so
// the client can review exactly what they're buying before they pay.
//
// `downloadable: true` marks products whose deliverables are files the user
// can download directly (logos, content, social posts, videos, website files,
// app binaries) — they don't need to go through the portal workflow to get
// their assets.

import {
  Crown, Rocket, Sparkles, Globe, Smartphone, Wallet, Bot, Palette,
  Search, FileText, Megaphone, BarChart3, Phone, Zap, MapPin, Star,
  Download, Store, Monitor, Tablet, Share2, Video,
} from "lucide-react";

export const SERVICE_CATALOG = [
  // ═════════════════════════════════════════════════════════
  // ─── SUBSCRIPTION PLANS ───────────────────────────────────
  // ═════════════════════════════════════════════════════════
  {
    id: "elite-monthly",
    name: "Elite Plan — Monthly",
    price: 1499,
    priceLabel: "$1,499/mo",
    category: "plan",
    icon: Crown,
    accent: "from-amber-400/20 to-fuchsia-400/10",
    tagline: "Done-for-you growth engine across multiple markets",
    description: "The complete growth package — 100% digital deliverables. Custom logo, full brand identity, built-to-order website, SEO/AEO optimization, rank engine, citations, backlinks and ongoing reporting.",
    features: [
      "Multiple markets / sites included",
      "Priority execution (jump the queue)",
      "Dedicated support & project lead",
      "Logo Generator — 10 concepts per market, pick 1",
      "Brand Generator — 10 mockups per market, pick up to 3",
      "Website Design — 10 packs per market, pick up to 3",
      "Website build per market (design, copy, imagery)",
      "On-page SEO + AEO optimization per site",
      "JSON-LD structured data per site",
      "Rank Engine — pages, citations & backlinks per market",
      "GSC sync, indexing & traffic tracking",
      "Ongoing content refresh & optimization",
      "Lead capture wiring per site",
      "Monthly execution & priority reporting",
      "All tools unlocked",
    ],
    statistics: [
      { label: "Avg. lead increase", value: "3.2×" },
      { label: "Time to page one", value: "60–90 days" },
      { label: "Markets included", value: "Multiple" },
      { label: "Iterations included", value: "2 free" },
    ],
    deliveryTime: "7 days",
    productId: "elite-monthly",
  },
  {
    id: "elite-annual",
    name: "Elite Plan — Annual",
    price: 14990,
    priceLabel: "$1,499/mo (billed annually)",
    category: "plan",
    icon: Crown,
    accent: "from-amber-400/20 to-fuchsia-400/10",
    tagline: "Elite plan billed annually — save 2 months",
    description: "Same Elite growth engine, billed annually at a discount. Full-service brand, web, sites, ranking, citations, backlinks & reporting with priority execution across multiple markets.",
    features: [
      "Everything in Elite Monthly",
      "Annual billing discount (save 2 months)",
      "Annual execution & monthly priority reporting",
    ],
    statistics: [
      { label: "Savings vs monthly", value: "$2,998/yr" },
      { label: "Avg. lead increase", value: "3.2×" },
      { label: "Time to page one", value: "60–90 days" },
    ],
    deliveryTime: "7 days",
    productId: "elite-annual",
  },
  {
    id: "pro-monthly",
    name: "Pro Plan — Monthly",
    price: 499,
    priceLabel: "$499/mo",
    category: "plan",
    icon: Rocket,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Full-service brand, website & ranking for one market",
    description: "Everything you need to launch and grow a single local site — brand kit, website build, SEO/AEO, rank engine, and monthly reporting.",
    features: [
      "1 market / site included",
      "Onboarding & business profile intake",
      "Logo Generator — 10 concepts, pick 1",
      "Brand Generator — 10 mockups, pick up to 3",
      "Website Design — 10 packs, pick up to 3",
      "Website build (design, copy, imagery)",
      "On-page SEO + AEO optimization",
      "JSON-LD structured data",
      "Rank Engine — SEO pages, citations & backlinks",
      "GSC sync & indexing",
      "Backlink outreach",
      "Lead capture wiring",
      "Monthly execution & reporting",
      "Portal access",
    ],
    statistics: [
      { label: "Avg. lead increase", value: "2.1×" },
      { label: "Time to page one", value: "90–120 days" },
      { label: "Markets included", value: "1" },
      { label: "Iterations included", value: "2 free" },
    ],
    deliveryTime: "7 days",
    productId: "pro-monthly",
  },
  {
    id: "pro-annual",
    name: "Pro Plan — Annual",
    price: 4990,
    priceLabel: "$416/mo (billed annually)",
    category: "plan",
    icon: Rocket,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Pro plan billed annually — save 2 months",
    description: "Same Pro plan, billed annually at a discount. Full-service brand, website & ranking engine for one market.",
    features: [
      "Everything in Pro Monthly",
      "Annual billing discount (save 2 months)",
    ],
    statistics: [
      { label: "Savings vs monthly", value: "$998/yr" },
      { label: "Avg. lead increase", value: "2.1×" },
      { label: "Time to page one", value: "90–120 days" },
    ],
    deliveryTime: "7 days",
    productId: "pro-annual",
  },

  // ═════════════════════════════════════════════════════════
  // ─── WEB PACKS (downloadable) ─────────────────────────────
  // ═════════════════════════════════════════════════════════
  {
    id: "web-pack-landing",
    name: "Landing Page Pack",
    price: 199,
    priceLabel: "$199",
    category: "web-pack",
    icon: Monitor,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "Single high-conversion landing page",
    description: "A single, high-conversion landing page with AI-written copy, lead capture form, and mobile-responsive design. Download the files and host it anywhere.",
    features: [
      "1 landing page (hero, benefits, CTA, form)",
      "AI-written copy for your industry",
      "Lead capture form wiring",
      "Mobile-responsive design",
      "Basic on-page SEO",
      "JSON-LD structured data",
      "Downloadable HTML/CSS/JS files",
      "Deploy to any host",
    ],
    statistics: [
      { label: "Pages", value: "1" },
      { label: "Delivery", value: "3 days" },
      { label: "Format", value: "HTML/CSS/JS" },
    ],
    deliveryTime: "3 days",
    productId: "web-pack-landing",
    downloadable: true,
  },
  {
    id: "web-pack-starter",
    name: "Starter Web Pack",
    price: 299,
    priceLabel: "$299",
    category: "web-pack",
    icon: Globe,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "3-page website with basic SEO — downloadable",
    description: "A compact 3-page website (Home, Services, Contact) with AI-generated logo, basic SEO, and lead capture. Download the files and host it yourself, or we can deploy it for you.",
    features: [
      "3-page website (Home, Services, Contact)",
      "AI Logo Generator — 3 concepts, pick 1",
      "AI-written copy for your industry",
      "AI-generated project imagery",
      "Mobile-responsive design",
      "Basic on-page SEO",
      "Lead capture form wiring",
      "Downloadable website files",
    ],
    statistics: [
      { label: "Pages", value: "3" },
      { label: "Logo concepts", value: "3" },
      { label: "Delivery", value: "5 days" },
    ],
    deliveryTime: "5 days",
    productId: "web-pack-starter",
    downloadable: true,
  },
  {
    id: "web-pack-pro",
    name: "Pro Web Pack",
    price: 599,
    priceLabel: "$599",
    category: "web-pack",
    icon: Globe,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "7-page website with full SEO/AEO — downloadable",
    description: "A complete 7-page website with 10 logo concepts, 10 brand mockups, full SEO/AEO optimization, and JSON-LD structured data. Download the files or let us deploy to a live URL.",
    features: [
      "7-page website (Home, About, Services, FAQ, Blog, Contact, Reviews)",
      "Logo Generator — 10 concepts, pick 1",
      "Brand Generator — 10 mockups, pick up to 3",
      "AI-written copy for all pages",
      "AI-generated project imagery",
      "Mobile-responsive design",
      "On-page SEO + AEO optimization",
      "JSON-LD structured data",
      "Lead capture form wiring",
      "Downloadable website files",
      "Optional deployment to live URL",
    ],
    statistics: [
      { label: "Pages", value: "7" },
      { label: "Logo concepts", value: "10" },
      { label: "Brand mockups", value: "10" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "web-pack-pro",
    downloadable: true,
  },
  {
    id: "web-pack-ecommerce",
    name: "E-Commerce Web Pack",
    price: 899,
    priceLabel: "$899",
    category: "web-pack",
    icon: Store,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "Full e-commerce site with product catalog & checkout",
    description: "A complete e-commerce website with product catalog, shopping cart, checkout integration, and full SEO/AEO. Sell products online with a conversion-optimized design.",
    features: [
      "Up to 15 pages + product catalog",
      "Shopping cart & checkout integration",
      "Payment gateway setup (Stripe/PayPal)",
      "Logo Generator — 10 concepts, pick 1",
      "Brand Generator — 10 mockups, pick up to 3",
      "AI-written product descriptions",
      "AI-generated product imagery",
      "Mobile-responsive design",
      "On-page SEO + AEO optimization",
      "JSON-LD product schema",
      "Lead capture & newsletter signup",
      "Downloadable source files",
    ],
    statistics: [
      { label: "Pages", value: "15+" },
      { label: "Products", value: "Unlimited" },
      { label: "Delivery", value: "10 days" },
    ],
    deliveryTime: "10 days",
    productId: "web-pack-ecommerce",
    downloadable: true,
  },

  // ═════════════════════════════════════════════════════════
  // ─── APP PACKS ────────────────────────────────────────────
  // ═════════════════════════════════════════════════════════
  {
    id: "app-pack-pwa",
    name: "PWA Pack",
    price: 299,
    priceLabel: "$299",
    category: "app-pack",
    icon: Smartphone,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Progressive Web App — installable from any browser",
    description: "Convert your website into a Progressive Web App that users can install from their browser — works on iOS, Android, and desktop. No app store review required.",
    features: [
      "PWA manifest & service worker",
      "Installable on iOS, Android & desktop",
      "Offline support",
      "Push notification setup",
      "App icons & splash screens",
      "Home screen install prompt",
      "No app store review needed",
      "Downloadable PWA files",
    ],
    statistics: [
      { label: "Platforms", value: "All" },
      { label: "App store review", value: "None" },
      { label: "Delivery", value: "3 days" },
    ],
    deliveryTime: "3 days",
    productId: "app-pack-pwa",
    downloadable: true,
  },
  {
    id: "app-pack-ios",
    name: "iOS App Pack",
    price: 499,
    priceLabel: "$499",
    category: "app-pack",
    icon: Smartphone,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Native iOS app — App Store submission included",
    description: "We package your site/brand into a native iOS app and submit it to the App Store. Includes app icons, splash screens, push notifications, and in-app lead capture.",
    features: [
      "Native iOS app build",
      "App Store submission & listing",
      "Push notification setup",
      "App icons & splash screens",
      "In-app lead capture",
      "Brand kit (logo, colors, typography)",
      "App Store Optimization (ASO)",
    ],
    statistics: [
      { label: "Platform", value: "iOS" },
      { label: "App store", value: "App Store" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "app-pack-ios",
  },
  {
    id: "app-pack-android",
    name: "Android App Pack",
    price: 499,
    priceLabel: "$499",
    category: "app-pack",
    icon: Tablet,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Native Android app — Google Play submission included",
    description: "We package your site/brand into a native Android app and submit it to Google Play. Includes app icons, splash screens, push notifications, and in-app lead capture.",
    features: [
      "Native Android app build",
      "Google Play submission & listing",
      "Push notification setup",
      "App icons & splash screens",
      "In-app lead capture",
      "Brand kit (logo, colors, typography)",
      "Play Store Optimization",
    ],
    statistics: [
      { label: "Platform", value: "Android" },
      { label: "App store", value: "Google Play" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "app-pack-android",
  },
  {
    id: "app-pack-both",
    name: "iOS + Android App Pack",
    price: 899,
    priceLabel: "$899",
    category: "app-pack",
    icon: Smartphone,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Both platforms — save $99 vs buying separately",
    description: "Get native iOS and Android apps from the same codebase. Both submitted to the App Store and Google Play. Best value for reaching all mobile users.",
    features: [
      "Everything in iOS App Pack",
      "Everything in Android App Pack",
      "Single codebase, both platforms",
      "App Store + Google Play submission",
      "Push notifications on both platforms",
      "App icons & splash screens",
      "In-app lead capture",
      "Save $99 vs buying separately",
    ],
    statistics: [
      { label: "Platforms", value: "iOS + Android" },
      { label: "App stores", value: "2" },
      { label: "Savings", value: "$99" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "app-pack-both",
  },

  // ═════════════════════════════════════════════════════════
  // ─── AI TOOLS (downloadable, $99 each) ────────────────────
  // ═════════════════════════════════════════════════════════
  {
    id: "ai-tool-logo",
    name: "AI Logo Generator",
    price: 99,
    priceLabel: "$99",
    category: "ai-tool",
    icon: Palette,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "10 custom logo concepts — download PNG + SVG",
    description: "Generate 10 custom logo concepts from your business name and industry. Pick your favorite and download the files in PNG and SVG format. No portal required.",
    features: [
      "10 custom logo concepts",
      "PNG + SVG file downloads",
      "Multiple color variations",
      "Light & dark versions",
      "Social media sizes included",
      "Unlimited regeneration",
      "Instant download after purchase",
    ],
    statistics: [
      { label: "Concepts", value: "10" },
      { label: "Formats", value: "PNG + SVG" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-logo",
    downloadable: true,
  },
  {
    id: "ai-tool-content",
    name: "AI Content Generator",
    price: 99,
    priceLabel: "$99",
    category: "ai-tool",
    icon: FileText,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "10 SEO-optimized articles — download as Markdown",
    description: "Generate 10 SEO-optimized blog articles, service pages, or location pages tailored to your niche. Download as Markdown files ready to publish anywhere.",
    features: [
      "10 articles per run",
      "1,200+ words per article",
      "SEO keyword integration",
      "Blog, service & FAQ formats",
      "Markdown file downloads",
      "Industry-specific copy",
      "Unlimited regeneration",
    ],
    statistics: [
      { label: "Articles per run", value: "10" },
      { label: "Avg. word count", value: "1,200+" },
      { label: "Format", value: "Markdown" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-content",
    downloadable: true,
  },
  {
    id: "ai-tool-social",
    name: "AI Social Media Generator",
    price: 99,
    priceLabel: "$99",
    category: "ai-tool",
    icon: Share2,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "30 social posts with images — download the full pack",
    description: "Generate 30 social media posts (image + caption) across Facebook, Instagram, Twitter/X, and LinkedIn. Download the full pack as a ZIP — ready to schedule.",
    features: [
      "30 social posts (image + caption)",
      "Facebook, Instagram, Twitter/X, LinkedIn",
      "AI-generated post imagery",
      "Caption + hashtag suggestions",
      "Brand-matched colors",
      "Downloadable ZIP pack",
      "Unlimited regeneration",
    ],
    statistics: [
      { label: "Posts", value: "30" },
      { label: "Platforms", value: "4" },
      { label: "Format", value: "ZIP" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-social",
    downloadable: true,
  },
  {
    id: "ai-tool-video",
    name: "AI Video Generator",
    price: 99,
    priceLabel: "$99",
    category: "ai-tool",
    icon: Video,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "3 promo videos — download as MP4",
    description: "Generate 3 short promotional videos for your business — hero reel, service highlight, and testimonial-style video. Download as MP4 files ready to post.",
    features: [
      "3 promo videos per run",
      "Hero reel, service highlight, testimonial",
      "AI-generated video content",
      "Brand-matched colors & text overlays",
      "MP4 file downloads (1080p)",
      "Social media formats (16:9 + 9:16)",
      "Unlimited regeneration",
    ],
    statistics: [
      { label: "Videos", value: "3" },
      { label: "Resolution", value: "1080p" },
      { label: "Format", value: "MP4" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-video",
    downloadable: true,
  },
  {
    id: "ai-tool-brand",
    name: "AI Brand Designer",
    price: 99,
    priceLabel: "$99",
    category: "ai-tool",
    icon: Palette,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Complete brand kit — download all assets",
    description: "Generate a full brand identity — positioning, logo concepts, color palette, typography, and brand voice — from your business name and industry. Download the complete kit.",
    features: [
      "10 logo concepts",
      "Color palette generation",
      "Typography pairing",
      "Brand voice & positioning",
      "Tagline suggestions",
      "Downloadable brand kit (ZIP)",
      "Unlimited regeneration",
    ],
    statistics: [
      { label: "Logo concepts", value: "10" },
      { label: "Format", value: "ZIP" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-brand",
    downloadable: true,
  },
  {
    id: "ai-tool-rank",
    name: "Rank Engine",
    price: 99,
    priceLabel: "$99/run",
    category: "ai-tool",
    icon: Search,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Generate & deploy SEO pages automatically",
    description: "An autonomous SEO page generator that creates city-service pages, deploys them, and tracks rankings. Each run produces optimized pages targeting your local keywords.",
    features: [
      "AI-generated city-service pages",
      "Keyword research & targeting",
      "On-page SEO optimization",
      "JSON-LD structured data",
      "Automatic deployment",
      "Ranking tracking",
      "Run receipt & report",
    ],
    statistics: [
      { label: "Pages per run", value: "10–50" },
      { label: "Avg. ranking lift", value: "+15 positions" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-rank",
  },
  {
    id: "ai-tool-citation",
    name: "Citation Builder",
    price: 99,
    priceLabel: "$99/run",
    category: "ai-tool",
    icon: MapPin,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Submit your business to 50+ local directories",
    description: "Automatically submits your business to local citation directories (Yelp, BBB, Angi, etc.) to boost local search visibility and build authority.",
    features: [
      "50+ directory submissions",
      "NAP consistency check",
      "Tier 1 & tier 2 directories",
      "Submission tracking",
      "Live link verification",
      "Run receipt & report",
    ],
    statistics: [
      { label: "Directories per run", value: "50+" },
      { label: "Avg. DA boost", value: "+8 points" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-citation",
  },
  {
    id: "ai-tool-backlink",
    name: "Backlink Outreach",
    price: 99,
    priceLabel: "$99/run",
    category: "ai-tool",
    icon: Megaphone,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Find & contact 50+ backlink prospects automatically",
    description: "Finds relevant backlink prospects in your niche, drafts personalized outreach emails, and tracks responses to build authority.",
    features: [
      "Prospect discovery (50+ per run)",
      "Personalized email drafting",
      "Relevance & DA scoring",
      "Outreach tracking",
      "Follow-up automation",
      "Run receipt & report",
    ],
    statistics: [
      { label: "Prospects per run", value: "50+" },
      { label: "Avg. response rate", value: "8–12%" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-backlink",
  },
  {
    id: "ai-tool-chatbot",
    name: "AI Lead Chatbot",
    price: 99,
    priceLabel: "$99/setup",
    category: "ai-tool",
    icon: Bot,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "24/7 AI chatbot that captures & qualifies leads",
    description: "An AI-powered chatbot for your website that answers visitor questions, qualifies leads, and books appointments — even when you're asleep.",
    features: [
      "AI-powered lead qualification",
      "Appointment booking",
      "FAQ answering",
      "Lead capture & routing",
      "CRM integration",
      "Setup receipt & config",
    ],
    statistics: [
      { label: "Lead capture rate", value: "+40%" },
      { label: "24/7 availability", value: "Always on" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-chatbot",
  },

  // ═════════════════════════════════════════════════════════
  // ─── INDIVIDUAL SERVICES ──────────────────────────────────
  // ═════════════════════════════════════════════════════════
  {
    id: "service-seo-audit",
    name: "SEO Audit",
    price: 149,
    priceLabel: "$149",
    category: "service",
    icon: BarChart3,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "Full technical & content SEO audit with PDF report",
    description: "A comprehensive SEO audit of your existing website — technical issues, content gaps, ranking opportunities, and a prioritized action plan.",
    features: [
      "Technical SEO audit",
      "Content gap analysis",
      "Keyword opportunity report",
      "Competitor analysis",
      "Prioritized action plan",
      "PDF report download",
    ],
    statistics: [
      { label: "Checks performed", value: "50+" },
      { label: "Format", value: "PDF" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "service-seo-audit",
    downloadable: true,
  },
  {
    id: "service-gbp",
    name: "Google Business Profile Setup",
    price: 300,
    priceLabel: "$300",
    category: "service",
    icon: MapPin,
    accent: "from-amber-500/20 to-lime-400/10",
    tagline: "Complete GBP setup & optimization",
    description: "Complete setup and optimization of your Google Business Profile for maximum local search visibility.",
    features: [
      "Profile creation & verification",
      "Category optimization",
      "Service area setup",
      "Photo upload & optimization",
      "Review request system",
      "Q&A setup",
    ],
    statistics: [
      { label: "Local pack visibility", value: "+60%" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "service-gbp",
  },
  {
    id: "service-call-tracking",
    name: "Call Tracking Number",
    price: 200,
    priceLabel: "$200",
    category: "service",
    icon: Phone,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Dedicated tracking number with analytics",
    description: "Dedicated tracking phone number with call recording and analytics to measure your lead flow.",
    features: [
      "Dedicated tracking number",
      "Call recording",
      "Call analytics dashboard",
      "Lead source attribution",
      "SMS notifications",
    ],
    statistics: [
      { label: "Call tracking", value: "100%" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "service-call-tracking",
  },
  {
    id: "service-rush",
    name: "Priority Rush Delivery",
    price: 500,
    priceLabel: "$500",
    category: "service",
    icon: Zap,
    accent: "from-amber-400/20 to-fuchsia-400/10",
    tagline: "Get your project delivered in 3 business days",
    description: "Jump the queue and get your website built and launched in 3 business days instead of the standard 7-day timeline.",
    features: [
      "3 business day delivery",
      "Priority queue position",
      "Dedicated builder",
      "Expedited review cycles",
    ],
    statistics: [
      { label: "Delivery", value: "3 days" },
      { label: "Priority", value: "Highest" },
    ],
    deliveryTime: "3 days",
    productId: "service-rush",
  },
  {
    id: "service-reviews",
    name: "Review Management System",
    price: 400,
    priceLabel: "$400",
    category: "service",
    icon: Star,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Automated review request system",
    description: "Automated review request system that sends review links to your customers after job completion, boosting your Google rating.",
    features: [
      "Automated review requests",
      "SMS + email delivery",
      "Review tracking dashboard",
      "Negative review alerts",
      "Response templates",
    ],
    statistics: [
      { label: "Review rate", value: "+35%" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "service-reviews",
  },
  {
    id: "deposit",
    name: "Done-For-You Service Deposit",
    price: 500,
    priceLabel: "$500 deposit",
    category: "service",
    icon: Wallet,
    accent: "from-amber-500/20 to-lime-400/10",
    tagline: "Lock in a done-for-you engagement",
    description: "A deposit that locks in a done-for-you engagement. Applied toward your total once the scope is finalized.",
    features: [
      "Discovery & scoping call",
      "Business profile intake",
      "Custom build plan",
      "Itemized scope of work",
      "Signed agreement",
      "Deposit credited to final invoice",
      "Dedicated project lead assigned",
    ],
    statistics: [
      { label: "Applied to total", value: "100%" },
      { label: "Discovery call", value: "15 min" },
    ],
    deliveryTime: "7 days",
    productId: "deposit",
  },
];

export const CATEGORIES = [
  { id: "plan", label: "Subscription Plans", icon: Crown },
  { id: "web-pack", label: "Web Packs", icon: Globe },
  { id: "app-pack", label: "App Packs", icon: Smartphone },
  { id: "ai-tool", label: "AI Tools", icon: Bot },
  { id: "service", label: "Individual Services", icon: Sparkles },
];

export function getServicesByCategory(cat) {
  return SERVICE_CATALOG.filter((s) => s.category === cat);
}