// Complete catalog of all services, plans, and à-la-carte tools offered.
// Used by the Pricing page, admin gallery, and checkout flow.
//
// PRICING MODEL (revised):
//   - Growth Packages → ONE-TIME (pay once, get all deliverables)
//   - Monthly Services → recurring subscriptions (ongoing execution)
//   - Web Packs / App Packs / AI Tools / Individual Services → one-time
//   - Free Products → $0, no checkout (direct portal access)
//
// `downloadable: true` marks products whose deliverables are files the user
// can download directly. `free: true` marks $0 products that bypass checkout.

import {
  Crown, Rocket, Sparkles, Globe, Smartphone, Wallet, Bot, Palette,
  Search, FileText, Megaphone, BarChart3, Phone, Zap, MapPin, Star,
  Store, Monitor, Tablet, Share2, Video, TrendingUp, RefreshCw,
  Bell, Send, Gift, Shield, Activity, Crosshair, Clock,
} from "lucide-react";

export const SERVICE_CATALOG = [
  // ═════════════════════════════════════════════════════════
  // ─── GROWTH PACKAGES (ONE-TIME) ──────────────────────────
  // ═════════════════════════════════════════════════════════
  {
    id: "elite-monthly",
    name: "Elite Growth Package",
    price: 2999,
    priceLabel: "$2,999 one-time",
    category: "package",
    icon: Crown,
    accent: "from-amber-400/20 to-fuchsia-400/10",
    tagline: "Done-for-you growth engine — brand, web, ranking & reporting (one-time)",
    description: "The complete growth package — 100% digital deliverables. Custom logo, full brand identity, built-to-order website, SEO/AEO optimization, rank engine, citations, backlinks and reporting. Pay once, get everything.",
    features: [
      "Multiple markets / sites included",
      "Priority execution (jump the queue)",
      "Dedicated support & project lead",
      "Logo Generator — 10 concepts per market, pick 1",
      "Brand Generator — 10 mockups per market, pick up to 3",
      "Website Design — 10 packs per market, pick up to 3",
      "Website build per market (design, copy, imagery)",
      "On-page SEO + AEO optimization per site",
      "JSON-LD structured data per site",
      "Rank Engine — pages, citations & backlinks per market",
      "GSC sync, indexing & traffic tracking",
      "Lead capture wiring per site",
      "All tools unlocked",
      "One-time payment — no recurring fees",
    ],
    statistics: [
      { label: "Avg. lead increase", value: "3.2×" },
      { label: "Time to page one", value: "60–90 days" },
      { label: "Markets included", value: "Multiple" },
      { label: "Payment", value: "One-time" },
    ],
    deliveryTime: "7 days",
    productId: "elite-monthly",
  },
  {
    id: "pro-monthly",
    name: "Pro Growth Package",
    price: 999,
    priceLabel: "$999 one-time",
    category: "package",
    icon: Rocket,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Full-service brand, website & ranking for one market (one-time)",
    description: "Everything you need to launch and grow a single local site — brand kit, website build, SEO/AEO, rank engine, and reporting. Pay once, get everything.",
    features: [
      "1 market / site included",
      "Onboarding & business profile intake",
      "Logo Generator — 10 concepts, pick 1",
      "Brand Generator — 10 mockups, pick up to 3",
      "Website Design — 10 packs, pick up to 3",
      "Website build (design, copy, imagery)",
      "On-page SEO + AEO optimization",
      "JSON-LD structured data",
      "Rank Engine — SEO pages, citations & backlinks",
      "GSC sync & indexing",
      "Backlink outreach",
      "Lead capture wiring",
      "One-time payment — no recurring fees",
    ],
    statistics: [
      { label: "Avg. lead increase", value: "2.1×" },
      { label: "Time to page one", value: "90–120 days" },
      { label: "Markets included", value: "1" },
      { label: "Payment", value: "One-time" },
    ],
    deliveryTime: "7 days",
    productId: "pro-monthly",
  },

  // ═════════════════════════════════════════════════════════
  // ─── MONTHLY SERVICES (recurring) ────────────────────────
  // Ongoing execution services — billed monthly. Each maps to
  // an existing autonomous tool in the portal.
  // ═════════════════════════════════════════════════════════
  {
    id: "monthly-seo-rank",
    name: "SEO Rank & Report",
    price: 149,
    priceLabel: "$149/mo",
    category: "monthly-service",
    icon: TrendingUp,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Monthly SEO page generation, ranking tracking & reports",
    description: "Autonomous rank engine that generates new SEO pages, tracks rankings, and delivers monthly reports. Keeps your site climbing toward page one.",
    features: [
      "AI-generated city-service pages (10–50/mo)",
      "Keyword research & targeting",
      "On-page SEO optimization",
      "JSON-LD structured data",
      "Automatic deployment",
      "Monthly ranking report",
      "Rank tracking dashboard",
    ],
    statistics: [
      { label: "Pages/mo", value: "10–50" },
      { label: "Avg. rank lift", value: "+15 positions" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-seo-rank",
  },
  {
    id: "monthly-citations",
    name: "Citation Building",
    price: 99,
    priceLabel: "$99/mo",
    category: "monthly-service",
    icon: MapPin,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Monthly directory submissions to 50+ local citations",
    description: "Autonomous citation builder that submits your business to local directories every month, boosting local search visibility and building authority.",
    features: [
      "50+ directory submissions/mo",
      "NAP consistency check",
      "Tier 1 & tier 2 directories",
      "Submission tracking",
      "Live link verification",
      "Monthly report",
    ],
    statistics: [
      { label: "Directories/mo", value: "50+" },
      { label: "Avg. DA boost", value: "+8 points" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-citations",
  },
  {
    id: "monthly-backlinks",
    name: "Backlink Outreach",
    price: 149,
    priceLabel: "$149/mo",
    category: "monthly-service",
    icon: Megaphone,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Monthly prospect discovery & personalized outreach",
    description: "Finds relevant backlink prospects, drafts personalized outreach emails, and tracks responses — every month, building authority at scale.",
    features: [
      "50+ prospects discovered/mo",
      "Personalized email drafting",
      "Relevance & DA scoring",
      "Outreach tracking",
      "Follow-up automation",
      "Monthly report",
    ],
    statistics: [
      { label: "Prospects/mo", value: "50+" },
      { label: "Response rate", value: "8–12%" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-backlinks",
  },
  {
    id: "monthly-content",
    name: "Content Generation",
    price: 99,
    priceLabel: "$99/mo",
    category: "monthly-service",
    icon: FileText,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Monthly SEO-optimized articles & page refreshes",
    description: "Autonomous content engine that generates blog articles, service pages, and FAQ content tailored to your niche — and refreshes stale pages.",
    features: [
      "10 articles/mo (1,200+ words each)",
      "SEO keyword integration",
      "Blog, service & FAQ formats",
      "Stale content refresh",
      "Industry-specific copy",
      "Monthly report",
    ],
    statistics: [
      { label: "Articles/mo", value: "10" },
      { label: "Avg. word count", value: "1,200+" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-content",
  },
  {
    id: "monthly-social",
    name: "Social Media Management",
    price: 149,
    priceLabel: "$149/mo",
    category: "monthly-service",
    icon: Share2,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Monthly social posts with images across all platforms",
    description: "Autonomous social media generator that creates posts with images and captions across Facebook, Instagram, Twitter/X, and LinkedIn every month.",
    features: [
      "30 social posts/mo (image + caption)",
      "Facebook, Instagram, Twitter/X, LinkedIn",
      "AI-generated post imagery",
      "Caption + hashtag suggestions",
      "Brand-matched colors",
      "Monthly report",
    ],
    statistics: [
      { label: "Posts/mo", value: "30" },
      { label: "Platforms", value: "4" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-social",
  },
  {
    id: "monthly-gsc",
    name: "GSC Monitoring & Indexing",
    price: 99,
    priceLabel: "$99/mo",
    category: "monthly-service",
    icon: Search,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Monthly GSC sync, indexing requests & traffic tracking",
    description: "Autonomous GSC pipeline that syncs your properties, submits new pages for indexing, and tracks traffic — every month.",
    features: [
      "GSC property sync",
      "Indexing requests for new pages",
      "Sitemap submission & monitoring",
      "Traffic & impression tracking",
      "Index coverage reports",
      "Monthly report",
    ],
    statistics: [
      { label: "Indexing requests", value: "Unlimited" },
      { label: "Sync frequency", value: "Monthly" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-gsc",
  },
  {
    id: "monthly-reviews",
    name: "Review Management",
    price: 79,
    priceLabel: "$79/mo",
    category: "monthly-service",
    icon: Star,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Automated review requests & reputation monitoring",
    description: "Automated review request system that sends review links to your customers, tracks reviews, and alerts you to negative feedback.",
    features: [
      "Automated review requests",
      "SMS + email delivery",
      "Review tracking dashboard",
      "Negative review alerts",
      "Response templates",
      "Monthly report",
    ],
    statistics: [
      { label: "Review rate", value: "+35%" },
      { label: "Alerts", value: "Real-time" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-reviews",
  },
  {
    id: "monthly-chatbot",
    name: "AI Chatbot Management",
    price: 99,
    priceLabel: "$99/mo",
    category: "monthly-service",
    icon: Bot,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "24/7 AI chatbot optimization & lead routing",
    description: "Monthly chatbot management — lead qualification optimization, FAQ updates, appointment booking, and CRM integration.",
    features: [
      "AI-powered lead qualification",
      "Appointment booking",
      "FAQ answering & updates",
      "Lead capture & routing",
      "CRM integration",
      "Monthly optimization report",
    ],
    statistics: [
      { label: "Lead capture rate", value: "+40%" },
      { label: "Availability", value: "24/7" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-chatbot",
  },
  {
    id: "monthly-tech-seo",
    name: "Technical SEO Audits",
    price: 129,
    priceLabel: "$129/mo",
    category: "monthly-service",
    icon: Shield,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Monthly technical SEO audits & fix recommendations",
    description: "Autonomous technical SEO auditor that crawls your site, identifies issues, and delivers prioritized fix recommendations every month.",
    features: [
      "Full technical SEO crawl",
      "Core Web Vitals monitoring",
      "Schema validation",
      "Mobile-friendliness check",
      "Prioritized fix recommendations",
      "Monthly audit report",
    ],
    statistics: [
      { label: "Checks/mo", value: "50+" },
      { label: "Issues found", value: "Tracked" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-tech-seo",
  },
  {
    id: "monthly-competitor-intel",
    name: "Competitor Intelligence",
    price: 129,
    priceLabel: "$129/mo",
    category: "monthly-service",
    icon: Crosshair,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Monthly competitor analysis & gap exploitation",
    description: "Autonomous competitor analysis that identifies competitor strategies, content gaps, and ranking opportunities to exploit every month.",
    features: [
      "Competitor website analysis",
      "Content gap identification",
      "Keyword opportunity reports",
      "SERP weakness scoring",
      "Backlink gap analysis",
      "Monthly intelligence report",
    ],
    statistics: [
      { label: "Competitors tracked", value: "10+" },
      { label: "Gaps found/mo", value: "5–15" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-competitor-intel",
  },
  {
    id: "monthly-aeo",
    name: "AEO / AI Search Optimization",
    price: 149,
    priceLabel: "$149/mo",
    category: "monthly-service",
    icon: Sparkles,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Monthly AI-search visibility optimization & monitoring",
    description: "Autonomous AEO engine that optimizes your content for AI search engines (ChatGPT, Perplexity, Google AI), monitors visibility, and builds answer blocks.",
    features: [
      "AI-search answer block optimization",
      "AEO schema & topic modeling",
      "AI visibility monitoring",
      "Answer engine citation tracking",
      "Content optimization for LLMs",
      "Monthly AEO report",
    ],
    statistics: [
      { label: "AI engines tracked", value: "5+" },
      { label: "Citation rate", value: "+25%" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-aeo",
  },
  {
    id: "monthly-call-tracking",
    name: "Call Tracking & Analytics",
    price: 79,
    priceLabel: "$79/mo",
    category: "monthly-service",
    icon: Phone,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Dedicated tracking number with call recording & analytics",
    description: "Dedicated tracking phone number with call recording, analytics, and lead source attribution — billed monthly.",
    features: [
      "Dedicated tracking number",
      "Call recording",
      "Call analytics dashboard",
      "Lead source attribution",
      "SMS notifications",
      "Monthly analytics report",
    ],
    statistics: [
      { label: "Call tracking", value: "100%" },
      { label: "Recording", value: "Included" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-call-tracking",
  },
  {
    id: "monthly-gbp",
    name: "Google Business Profile Management",
    price: 99,
    priceLabel: "$99/mo",
    category: "monthly-service",
    icon: MapPin,
    accent: "from-amber-500/20 to-lime-400/10",
    tagline: "Monthly GBP posts, updates & optimization",
    description: "Autonomous GBP manager that posts updates, optimizes categories, responds to reviews, and tracks local pack visibility.",
    features: [
      "Monthly GBP posts",
      "Category & service area optimization",
      "Review response management",
      "Photo uploads & optimization",
      "Q&A monitoring & responses",
      "Monthly local pack report",
    ],
    statistics: [
      { label: "Local pack visibility", value: "+60%" },
      { label: "Posts/mo", value: "4+" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-gbp",
  },
  {
    id: "monthly-site-maintenance",
    name: "Website Maintenance",
    price: 99,
    priceLabel: "$99/mo",
    category: "monthly-service",
    icon: RefreshCw,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Monthly site updates, security & performance monitoring",
    description: "Autonomous site maintenance that keeps your website updated, secure, and fast — with monthly performance reports.",
    features: [
      "Security monitoring & patches",
      "Performance optimization",
      "Content updates & refreshes",
      "Uptime monitoring",
      "Backup verification",
      "Monthly maintenance report",
    ],
    statistics: [
      { label: "Uptime", value: "99.9%" },
      { label: "Response time", value: "<2s" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-site-maintenance",
  },
  {
    id: "monthly-lead-gen",
    name: "Lead Generation Pipeline",
    price: 199,
    priceLabel: "$199/mo",
    category: "monthly-service",
    icon: Zap,
    accent: "from-amber-400/20 to-fuchsia-400/10",
    tagline: "Monthly lead discovery, scoring & nurturing",
    description: "Autonomous lead generation engine that discovers high-value prospects, scores them, and nurtures them through the pipeline every month.",
    features: [
      "High-value prospect discovery",
      "Lead scoring & qualification",
      "Nurture sequence automation",
      "CRM pipeline sync",
      "Lead source attribution",
      "Monthly lead report",
    ],
    statistics: [
      { label: "Prospects/mo", value: "100+" },
      { label: "Qualified leads", value: "20–40" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-lead-gen",
  },
  {
    id: "monthly-backlink-followup",
    name: "Backlink Follow-up Sequence",
    price: 79,
    priceLabel: "$79/mo",
    category: "monthly-service",
    icon: Send,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Automated follow-up sequences for outreach prospects",
    description: "Autonomous follow-up engine that sends sequenced follow-up emails to backlink prospects, maximizing response rates.",
    features: [
      "Automated follow-up sequences",
      "Personalized follow-up emails",
      "Response tracking",
      "Reply rate optimization",
      "Sequence scheduling",
      "Monthly follow-up report",
    ],
    statistics: [
      { label: "Follow-up rate", value: "+45%" },
      { label: "Sequences/mo", value: "Unlimited" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-backlink-followup",
  },
  {
    id: "monthly-rank-alerts",
    name: "Rank Alert Monitoring",
    price: 69,
    priceLabel: "$69/mo",
    category: "monthly-service",
    icon: Bell,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Real-time rank drop alerts & recovery recommendations",
    description: "Autonomous rank monitor that watches your keyword positions, alerts you to drops, and recommends recovery actions.",
    features: [
      "Daily rank position tracking",
      "Real-time drop alerts",
      "Recovery recommendations",
      "Competitor position monitoring",
      "SERP feature tracking",
      "Monthly alert summary",
    ],
    statistics: [
      { label: "Keywords tracked", value: "Unlimited" },
      { label: "Alert speed", value: "Real-time" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-rank-alerts",
  },
  {
    id: "monthly-content-distribution",
    name: "Content Distribution",
    price: 99,
    priceLabel: "$99/mo",
    category: "monthly-service",
    icon: Activity,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Monthly content syndication across web & social channels",
    description: "Autonomous content distribution engine that syndicates your content across web channels, social platforms, and content networks.",
    features: [
      "Multi-channel content syndication",
      "Social media cross-posting",
      "Content network distribution",
      "IndexNow submission",
      "RSS & feed management",
      "Monthly distribution report",
    ],
    statistics: [
      { label: "Channels", value: "10+" },
      { label: "Posts distributed/mo", value: "50+" },
      { label: "Report", value: "Monthly" },
    ],
    deliveryTime: "Ongoing",
    productId: "monthly-content-distribution",
  },

  // ═════════════════════════════════════════════════════════
  // ─── FREE PRODUCTS ($0, no checkout) ─────────────────────
  // ═════════════════════════════════════════════════════════
  {
    id: "free-seo-audit",
    name: "Free SEO Audit",
    price: 0,
    priceLabel: "Free",
    category: "free",
    icon: Gift,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Instant technical & content SEO audit — no cost",
    description: "Get a free SEO audit of your website — technical issues, content gaps, and quick-win opportunities. No signup required.",
    features: [
      "Technical SEO scan",
      "Content gap analysis",
      "Keyword opportunity report",
      "Quick-win recommendations",
      "Instant results",
      "No credit card required",
    ],
    statistics: [
      { label: "Checks", value: "50+" },
      { label: "Delivery", value: "Instant" },
      { label: "Cost", value: "Free" },
    ],
    deliveryTime: "Instant",
    productId: "free-seo-audit",
    free: true,
  },
  {
    id: "free-business-names",
    name: "Free Business Name Generator",
    price: 0,
    priceLabel: "Free",
    category: "free",
    icon: Sparkles,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "AI-powered business name ideas with domain check — free",
    description: "Generate creative business name ideas with viral potential scoring, domain availability check, and trademark screening — completely free.",
    features: [
      "20 AI-generated name ideas",
      "Viral potential scoring",
      "Domain availability check",
      "Trademark screening",
      "State registry check",
      "Google uniqueness check",
    ],
    statistics: [
      { label: "Names generated", value: "20" },
      { label: "Delivery", value: "Instant" },
      { label: "Cost", value: "Free" },
    ],
    deliveryTime: "Instant",
    productId: "free-business-names",
    free: true,
  },
  {
    id: "free-domain-check",
    name: "Free Domain Availability Check",
    price: 0,
    priceLabel: "Free",
    category: "free",
    icon: Globe,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Check any domain's availability instantly — free",
    description: "Check domain availability with RDAP lookup, pricing, and purchase links. No cost, no signup.",
    features: [
      "Instant RDAP availability check",
      "Domain pricing lookup",
      "Registrar purchase link",
      "Bulk domain check",
      "TLD suggestions",
      "No signup required",
    ],
    statistics: [
      { label: "Check speed", value: "Instant" },
      { label: "TLDs supported", value: "All" },
      { label: "Cost", value: "Free" },
    ],
    deliveryTime: "Instant",
    productId: "free-domain-check",
    free: true,
  },
  {
    id: "free-logo-concept",
    name: "Free Logo Concept",
    price: 0,
    priceLabel: "Free",
    category: "free",
    icon: Palette,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "1 free AI logo concept — no credit card",
    description: "Try our AI logo generator with 1 free concept. See the quality before you buy the full 10-concept pack.",
    features: [
      "1 AI-generated logo concept",
      "PNG download",
      "Your business name & industry",
      "Color variation",
      "No watermark",
      "No credit card required",
    ],
    statistics: [
      { label: "Concepts", value: "1" },
      { label: "Delivery", value: "Instant" },
      { label: "Cost", value: "Free" },
    ],
    deliveryTime: "Instant",
    productId: "free-logo-concept",
    free: true,
  },
  {
    id: "free-competitor-scan",
    name: "Free Competitor Scan",
    price: 0,
    priceLabel: "Free",
    category: "free",
    icon: Crosshair,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Basic competitor analysis — see who's ranking & why",
    description: "Get a free basic competitor scan — see who's ranking for your keywords, their content gaps, and quick opportunities.",
    features: [
      "Top 10 competitor identification",
      "Content gap summary",
      "Keyword overlap report",
      "Quick-win opportunities",
      "Basic SERP analysis",
      "No credit card required",
    ],
    statistics: [
      { label: "Competitors scanned", value: "10" },
      { label: "Delivery", value: "Instant" },
      { label: "Cost", value: "Free" },
    ],
    deliveryTime: "Instant",
    productId: "free-competitor-scan",
    free: true,
  },
  {
    id: "free-gbp-check",
    name: "Free GBP Health Check",
    price: 0,
    priceLabel: "Free",
    category: "free",
    icon: MapPin,
    accent: "from-amber-500/20 to-lime-400/10",
    tagline: "Audit your Google Business Profile — free",
    description: "Get a free health check of your Google Business Profile — find optimization gaps and local pack opportunities.",
    features: [
      "GBP completeness audit",
      "Category optimization check",
      "Photo & review analysis",
      "Local pack opportunity scan",
      "Quick-fix recommendations",
      "No credit card required",
    ],
    statistics: [
      { label: "Checks", value: "25+" },
      { label: "Delivery", value: "Instant" },
      { label: "Cost", value: "Free" },
    ],
    deliveryTime: "Instant",
    productId: "free-gbp-check",
    free: true,
  },
  {
    id: "free-keyword-research",
    name: "Free Keyword Research",
    price: 0,
    priceLabel: "Free",
    category: "free",
    icon: Search,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Basic keyword research report for your niche — free",
    description: "Get a free keyword research report — search volume, CPC, and ranking difficulty for your industry.",
    features: [
      "20 target keywords",
      "Search volume estimates",
      "CPC & lead value data",
      "Ranking difficulty scores",
      "Keyword opportunity map",
      "No credit card required",
    ],
    statistics: [
      { label: "Keywords", value: "20" },
      { label: "Delivery", value: "Instant" },
      { label: "Cost", value: "Free" },
    ],
    deliveryTime: "Instant",
    productId: "free-keyword-research",
    free: true,
  },
  {
    id: "free-speed-test",
    name: "Free Website Speed Test",
    price: 0,
    priceLabel: "Free",
    category: "free",
    icon: Zap,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Test your website speed & performance — free",
    description: "Get a free website speed test — Core Web Vitals, load time, and performance recommendations.",
    features: [
      "Core Web Vitals report",
      "Page load time analysis",
      "Performance score",
      "Optimization recommendations",
      "Mobile & desktop test",
      "No credit card required",
    ],
    statistics: [
      { label: "Metrics", value: "10+" },
      { label: "Delivery", value: "Instant" },
      { label: "Cost", value: "Free" },
    ],
    deliveryTime: "Instant",
    productId: "free-speed-test",
    free: true,
  },

  // ═════════════════════════════════════════════════════════
  // ─── WEB PACKS (one-time, downloadable) ──────────────────
  // ═════════════════════════════════════════════════════════
  {
    id: "web-pack-landing",
    name: "Landing Page Pack",
    price: 199,
    priceLabel: "$199",
    category: "web-pack",
    icon: Monitor,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "Single high-conversion landing page",
    description: "A single, high-conversion landing page with AI-written copy, lead capture form, and mobile-responsive design. Download the files and host it anywhere.",
    features: [
      "1 landing page (hero, benefits, CTA, form)",
      "AI-written copy for your industry",
      "Lead capture form wiring",
      "Mobile-responsive design",
      "Basic on-page SEO",
      "JSON-LD structured data",
      "Downloadable HTML/CSS/JS files",
      "Deploy to any host",
    ],
    statistics: [
      { label: "Pages", value: "1" },
      { label: "Delivery", value: "3 days" },
      { label: "Format", value: "HTML/CSS/JS" },
    ],
    deliveryTime: "3 days",
    productId: "web-pack-landing",
    downloadable: true,
  },
  {
    id: "web-pack-starter",
    name: "Starter Web Pack",
    price: 299,
    priceLabel: "$299",
    category: "web-pack",
    icon: Globe,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "3-page website with basic SEO — downloadable",
    description: "A compact 3-page website (Home, Services, Contact) with AI-generated logo, basic SEO, and lead capture. Download the files and host it yourself, or we can deploy it for you.",
    features: [
      "3-page website (Home, Services, Contact)",
      "AI Logo Generator — 3 concepts, pick 1",
      "AI-written copy for your industry",
      "AI-generated project imagery",
      "Mobile-responsive design",
      "Basic on-page SEO",
      "Lead capture form wiring",
      "Downloadable website files",
    ],
    statistics: [
      { label: "Pages", value: "3" },
      { label: "Logo concepts", value: "3" },
      { label: "Delivery", value: "5 days" },
    ],
    deliveryTime: "5 days",
    productId: "web-pack-starter",
    downloadable: true,
  },
  {
    id: "web-pack-pro",
    name: "Pro Web Pack",
    price: 599,
    priceLabel: "$599",
    category: "web-pack",
    icon: Globe,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "7-page website with full SEO/AEO — downloadable",
    description: "A complete 7-page website with 10 logo concepts, 10 brand mockups, full SEO/AEO optimization, and JSON-LD structured data. Download the files or let us deploy to a live URL.",
    features: [
      "7-page website (Home, About, Services, FAQ, Blog, Contact, Reviews)",
      "Logo Generator — 10 concepts, pick 1",
      "Brand Generator — 10 mockups, pick up to 3",
      "AI-written copy for all pages",
      "AI-generated project imagery",
      "Mobile-responsive design",
      "On-page SEO + AEO optimization",
      "JSON-LD structured data",
      "Lead capture form wiring",
      "Downloadable website files",
      "Optional deployment to live URL",
    ],
    statistics: [
      { label: "Pages", value: "7" },
      { label: "Logo concepts", value: "10" },
      { label: "Brand mockups", value: "10" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "web-pack-pro",
    downloadable: true,
  },
  {
    id: "web-pack-ecommerce",
    name: "E-Commerce Web Pack",
    price: 899,
    priceLabel: "$899",
    category: "web-pack",
    icon: Store,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "Full e-commerce site with product catalog & checkout",
    description: "A complete e-commerce website with product catalog, shopping cart, checkout integration, and full SEO/AEO. Sell products online with a conversion-optimized design.",
    features: [
      "Up to 15 pages + product catalog",
      "Shopping cart & checkout integration",
      "Payment gateway setup (Stripe/PayPal)",
      "Logo Generator — 10 concepts, pick 1",
      "Brand Generator — 10 mockups, pick up to 3",
      "AI-written product descriptions",
      "AI-generated product imagery",
      "Mobile-responsive design",
      "On-page SEO + AEO optimization",
      "JSON-LD product schema",
      "Lead capture & newsletter signup",
      "Downloadable source files",
    ],
    statistics: [
      { label: "Pages", value: "15+" },
      { label: "Products", value: "Unlimited" },
      { label: "Delivery", value: "10 days" },
    ],
    deliveryTime: "10 days",
    productId: "web-pack-ecommerce",
    downloadable: true,
  },

  // ═════════════════════════════════════════════════════════
  // ─── APP PACKS (one-time) ─────────────────────────────────
  // ═════════════════════════════════════════════════════════
  {
    id: "app-pack-pwa",
    name: "PWA Pack",
    price: 299,
    priceLabel: "$299",
    category: "app-pack",
    icon: Smartphone,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Progressive Web App — installable from any browser",
    description: "Convert your website into a Progressive Web App that users can install from their browser — works on iOS, Android, and desktop. No app store review required.",
    features: [
      "PWA manifest & service worker",
      "Installable on iOS, Android & desktop",
      "Offline support",
      "Push notification setup",
      "App icons & splash screens",
      "Home screen install prompt",
      "No app store review needed",
      "Downloadable PWA files",
    ],
    statistics: [
      { label: "Platforms", value: "All" },
      { label: "App store review", value: "None" },
      { label: "Delivery", value: "3 days" },
    ],
    deliveryTime: "3 days",
    productId: "app-pack-pwa",
    downloadable: true,
  },
  {
    id: "app-pack-ios",
    name: "iOS App Pack",
    price: 499,
    priceLabel: "$499",
    category: "app-pack",
    icon: Smartphone,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Native iOS app — App Store submission included",
    description: "We package your site/brand into a native iOS app and submit it to the App Store. Includes app icons, splash screens, push notifications, and in-app lead capture.",
    features: [
      "Native iOS app build",
      "App Store submission & listing",
      "Push notification setup",
      "App icons & splash screens",
      "In-app lead capture",
      "Brand kit (logo, colors, typography)",
      "App Store Optimization (ASO)",
    ],
    statistics: [
      { label: "Platform", value: "iOS" },
      { label: "App store", value: "App Store" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "app-pack-ios",
  },
  {
    id: "app-pack-android",
    name: "Android App Pack",
    price: 499,
    priceLabel: "$499",
    category: "app-pack",
    icon: Tablet,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Native Android app — Google Play submission included",
    description: "We package your site/brand into a native Android app and submit it to Google Play. Includes app icons, splash screens, push notifications, and in-app lead capture.",
    features: [
      "Native Android app build",
      "Google Play submission & listing",
      "Push notification setup",
      "App icons & splash screens",
      "In-app lead capture",
      "Brand kit (logo, colors, typography)",
      "Play Store Optimization",
    ],
    statistics: [
      { label: "Platform", value: "Android" },
      { label: "App store", value: "Google Play" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "app-pack-android",
  },
  {
    id: "app-pack-both",
    name: "iOS + Android App Pack",
    price: 899,
    priceLabel: "$899",
    category: "app-pack",
    icon: Smartphone,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Both platforms — save $99 vs buying separately",
    description: "Get native iOS and Android apps from the same codebase. Both submitted to the App Store and Google Play. Best value for reaching all mobile users.",
    features: [
      "Everything in iOS App Pack",
      "Everything in Android App Pack",
      "Single codebase, both platforms",
      "App Store + Google Play submission",
      "Push notifications on both platforms",
      "App icons & splash screens",
      "In-app lead capture",
      "Save $99 vs buying separately",
    ],
    statistics: [
      { label: "Platforms", value: "iOS + Android" },
      { label: "App stores", value: "2" },
      { label: "Savings", value: "$99" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "app-pack-both",
  },

  // ═════════════════════════════════════════════════════════
  // ─── AI TOOLS (one-time, downloadable, $99 each) ──────────
  // ═════════════════════════════════════════════════════════
  {
    id: "ai-tool-logo",
    name: "AI Logo Generator",
    price: 99,
    priceLabel: "$99",
    category: "ai-tool",
    icon: Palette,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "10 custom logo concepts — download PNG + SVG",
    description: "Generate 10 custom logo concepts from your business name and industry. Pick your favorite and download the files in PNG and SVG format. No portal required.",
    features: [
      "10 custom logo concepts",
      "PNG + SVG file downloads",
      "Multiple color variations",
      "Light & dark versions",
      "Social media sizes included",
      "Unlimited regeneration",
      "Instant download after purchase",
    ],
    statistics: [
      { label: "Concepts", value: "10" },
      { label: "Formats", value: "PNG + SVG" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-logo",
    downloadable: true,
  },
  {
    id: "ai-tool-content",
    name: "AI Content Generator",
    price: 99,
    priceLabel: "$99",
    category: "ai-tool",
    icon: FileText,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "10 SEO-optimized articles — download as Markdown",
    description: "Generate 10 SEO-optimized blog articles, service pages, or location pages tailored to your niche. Download as Markdown files ready to publish anywhere.",
    features: [
      "10 articles per run",
      "1,200+ words per article",
      "SEO keyword integration",
      "Blog, service & FAQ formats",
      "Markdown file downloads",
      "Industry-specific copy",
      "Unlimited regeneration",
    ],
    statistics: [
      { label: "Articles per run", value: "10" },
      { label: "Avg. word count", value: "1,200+" },
      { label: "Format", value: "Markdown" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-content",
    downloadable: true,
  },
  {
    id: "ai-tool-social",
    name: "AI Social Media Generator",
    price: 99,
    priceLabel: "$99",
    category: "ai-tool",
    icon: Share2,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "30 social posts with images — download the full pack",
    description: "Generate 30 social media posts (image + caption) across Facebook, Instagram, Twitter/X, and LinkedIn. Download the full pack as a ZIP — ready to schedule.",
    features: [
      "30 social posts (image + caption)",
      "Facebook, Instagram, Twitter/X, LinkedIn",
      "AI-generated post imagery",
      "Caption + hashtag suggestions",
      "Brand-matched colors",
      "Downloadable ZIP pack",
      "Unlimited regeneration",
    ],
    statistics: [
      { label: "Posts", value: "30" },
      { label: "Platforms", value: "4" },
      { label: "Format", value: "ZIP" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-social",
    downloadable: true,
  },
  {
    id: "ai-tool-video",
    name: "AI Video Generator",
    price: 99,
    priceLabel: "$99",
    category: "ai-tool",
    icon: Video,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "3 promo videos — download as MP4",
    description: "Generate 3 short promotional videos for your business — hero reel, service highlight, and testimonial-style video. Download as MP4 files ready to post.",
    features: [
      "3 promo videos per run",
      "Hero reel, service highlight, testimonial",
      "AI-generated video content",
      "Brand-matched colors & text overlays",
      "MP4 file downloads (1080p)",
      "Social media formats (16:9 + 9:16)",
      "Unlimited regeneration",
    ],
    statistics: [
      { label: "Videos", value: "3" },
      { label: "Resolution", value: "1080p" },
      { label: "Format", value: "MP4" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-video",
    downloadable: true,
  },
  {
    id: "ai-tool-brand",
    name: "AI Brand Designer",
    price: 99,
    priceLabel: "$99",
    category: "ai-tool",
    icon: Palette,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Complete brand kit — download all assets",
    description: "Generate a full brand identity — positioning, logo concepts, color palette, typography, and brand voice — from your business name and industry. Download the complete kit.",
    features: [
      "10 logo concepts",
      "Color palette generation",
      "Typography pairing",
      "Brand voice & positioning",
      "Tagline suggestions",
      "Downloadable brand kit (ZIP)",
      "Unlimited regeneration",
    ],
    statistics: [
      { label: "Logo concepts", value: "10" },
      { label: "Format", value: "ZIP" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-brand",
    downloadable: true,
  },
  {
    id: "ai-tool-rank",
    name: "Rank Engine",
    price: 99,
    priceLabel: "$99/run",
    category: "ai-tool",
    icon: Search,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Generate & deploy SEO pages automatically",
    description: "An autonomous SEO page generator that creates city-service pages, deploys them, and tracks rankings. Each run produces optimized pages targeting your local keywords.",
    features: [
      "AI-generated city-service pages",
      "Keyword research & targeting",
      "On-page SEO optimization",
      "JSON-LD structured data",
      "Automatic deployment",
      "Ranking tracking",
      "Run receipt & report",
    ],
    statistics: [
      { label: "Pages per run", value: "10–50" },
      { label: "Avg. ranking lift", value: "+15 positions" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-rank",
  },
  {
    id: "ai-tool-citation",
    name: "Citation Builder",
    price: 99,
    priceLabel: "$99/run",
    category: "ai-tool",
    icon: MapPin,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Submit your business to 50+ local directories",
    description: "Automatically submits your business to local citation directories (Yelp, BBB, Angi, etc.) to boost local search visibility and build authority.",
    features: [
      "50+ directory submissions",
      "NAP consistency check",
      "Tier 1 & tier 2 directories",
      "Submission tracking",
      "Live link verification",
      "Run receipt & report",
    ],
    statistics: [
      { label: "Directories per run", value: "50+" },
      { label: "Avg. DA boost", value: "+8 points" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-citation",
  },
  {
    id: "ai-tool-backlink",
    name: "Backlink Outreach",
    price: 99,
    priceLabel: "$99/run",
    category: "ai-tool",
    icon: Megaphone,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Find & contact 50+ backlink prospects automatically",
    description: "Finds relevant backlink prospects in your niche, drafts personalized outreach emails, and tracks responses to build authority.",
    features: [
      "Prospect discovery (50+ per run)",
      "Personalized email drafting",
      "Relevance & DA scoring",
      "Outreach tracking",
      "Follow-up automation",
      "Run receipt & report",
    ],
    statistics: [
      { label: "Prospects per run", value: "50+" },
      { label: "Avg. response rate", value: "8–12%" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-backlink",
  },
  {
    id: "ai-tool-chatbot",
    name: "AI Lead Chatbot",
    price: 99,
    priceLabel: "$99/setup",
    category: "ai-tool",
    icon: Bot,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "24/7 AI chatbot that captures & qualifies leads",
    description: "An AI-powered chatbot for your website that answers visitor questions, qualifies leads, and books appointments — even when you're asleep.",
    features: [
      "AI-powered lead qualification",
      "Appointment booking",
      "FAQ answering",
      "Lead capture & routing",
      "CRM integration",
      "Setup receipt & config",
    ],
    statistics: [
      { label: "Lead capture rate", value: "+40%" },
      { label: "24/7 availability", value: "Always on" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "ai-tool-chatbot",
  },

  // ═════════════════════════════════════════════════════════
  // ─── INDIVIDUAL SERVICES (one-time) ──────────────────────
  // ═════════════════════════════════════════════════════════
  {
    id: "service-seo-audit",
    name: "SEO Audit",
    price: 149,
    priceLabel: "$149",
    category: "service",
    icon: BarChart3,
    accent: "from-sky-500/20 to-lime-400/10",
    tagline: "Full technical & content SEO audit with PDF report",
    description: "A comprehensive SEO audit of your existing website — technical issues, content gaps, ranking opportunities, and a prioritized action plan.",
    features: [
      "Technical SEO audit",
      "Content gap analysis",
      "Keyword opportunity report",
      "Competitor analysis",
      "Prioritized action plan",
      "PDF report download",
    ],
    statistics: [
      { label: "Checks performed", value: "50+" },
      { label: "Format", value: "PDF" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "service-seo-audit",
    downloadable: true,
  },
  {
    id: "service-gbp",
    name: "Google Business Profile Setup",
    price: 300,
    priceLabel: "$300",
    category: "service",
    icon: MapPin,
    accent: "from-amber-500/20 to-lime-400/10",
    tagline: "Complete GBP setup & optimization",
    description: "Complete setup and optimization of your Google Business Profile for maximum local search visibility.",
    features: [
      "Profile creation & verification",
      "Category optimization",
      "Service area setup",
      "Photo upload & optimization",
      "Review request system",
      "Q&A setup",
    ],
    statistics: [
      { label: "Local pack visibility", value: "+60%" },
      { label: "Delivery", value: "7 days" },
    ],
    deliveryTime: "7 days",
    productId: "service-gbp",
  },
  {
    id: "service-call-tracking",
    name: "Call Tracking Number",
    price: 200,
    priceLabel: "$200",
    category: "service",
    icon: Phone,
    accent: "from-violet-500/20 to-lime-400/10",
    tagline: "Dedicated tracking number with analytics",
    description: "Dedicated tracking phone number with call recording and analytics to measure your lead flow.",
    features: [
      "Dedicated tracking number",
      "Call recording",
      "Call analytics dashboard",
      "Lead source attribution",
      "SMS notifications",
    ],
    statistics: [
      { label: "Call tracking", value: "100%" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "service-call-tracking",
  },
  {
    id: "service-rush",
    name: "Priority Rush Delivery",
    price: 500,
    priceLabel: "$500",
    category: "service",
    icon: Zap,
    accent: "from-amber-400/20 to-fuchsia-400/10",
    tagline: "Get your project delivered in 3 business days",
    description: "Jump the queue and get your website built and launched in 3 business days instead of the standard 7-day timeline.",
    features: [
      "3 business day delivery",
      "Priority queue position",
      "Dedicated builder",
      "Expedited review cycles",
    ],
    statistics: [
      { label: "Delivery", value: "3 days" },
      { label: "Priority", value: "Highest" },
    ],
    deliveryTime: "3 days",
    productId: "service-rush",
  },
  {
    id: "service-reviews",
    name: "Review Management System",
    price: 400,
    priceLabel: "$400",
    category: "service",
    icon: Star,
    accent: "from-lime-400/20 to-emerald-400/10",
    tagline: "Automated review request system",
    description: "Automated review request system that sends review links to your customers after job completion, boosting your Google rating.",
    features: [
      "Automated review requests",
      "SMS + email delivery",
      "Review tracking dashboard",
      "Negative review alerts",
      "Response templates",
    ],
    statistics: [
      { label: "Review rate", value: "+35%" },
      { label: "Delivery", value: "Instant" },
    ],
    deliveryTime: "Instant",
    productId: "service-reviews",
  },
  {
    id: "deposit",
    name: "Done-For-You Service Deposit",
    price: 500,
    priceLabel: "$500 deposit",
    category: "service",
    icon: Wallet,
    accent: "from-amber-500/20 to-lime-400/10",
    tagline: "Lock in a done-for-you engagement",
    description: "A deposit that locks in a done-for-you engagement. Applied toward your total once the scope is finalized.",
    features: [
      "Discovery & scoping call",
      "Business profile intake",
      "Custom build plan",
      "Itemized scope of work",
      "Signed agreement",
      "Deposit credited to final invoice",
      "Dedicated project lead assigned",
    ],
    statistics: [
      { label: "Applied to total", value: "100%" },
      { label: "Discovery call", value: "15 min" },
    ],
    deliveryTime: "7 days",
    productId: "deposit",
  },
];

export const CATEGORIES = [
  { id: "package", label: "Growth Packages (One-Time)", icon: Crown },
  { id: "monthly-service", label: "Monthly Services", icon: Clock },
  { id: "free", label: "Free Products", icon: Gift },
  { id: "web-pack", label: "Web Packs", icon: Globe },
  { id: "app-pack", label: "App Packs", icon: Smartphone },
  { id: "ai-tool", label: "AI Tools", icon: Bot },
  { id: "service", label: "Individual Services", icon: Sparkles },
];

export function getServicesByCategory(cat) {
  return SERVICE_CATALOG.filter((s) => s.category === cat);
}

export function getFreeProducts() {
  return SERVICE_CATALOG.filter((s) => s.free === true);
}

export function getMonthlyServices() {
  return SERVICE_CATALOG.filter((s) => s.category === "monthly-service");
}

export function getPackages() {
  return SERVICE_CATALOG.filter((s) => s.category === "package");
}