import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';

// Seeds the SeoStandardChecklist entity with every known SEO method.
// Idempotent: skips if already seeded.
export default async function(req) {
  try {
    const base44 = createClientFromRequest(req);
    const svc = base44.asServiceRole;

    const existing = await svc.entities.SeoStandardChecklist.list('-created_date', 1);
    if (existing.length > 0) {
      return Response.json({ ok: true, message: 'Already seeded', count: existing.length });
    }

    const methods = [
      // ===== TECHNICAL SEO =====
      { method_name: 'XML Sitemap Generation + Auto-Submission', category: 'technical', subcategory: 'Crawling', description: 'Generate sitemap.xml and auto-submit to Google Search Console for every site.', priority: 'critical', automation_frequency: 'one_time', automation_capable: true, function_name: 'submitToGSC', impact_score: 10, difficulty: 'easy', google_confirmed: true },
      { method_name: 'robots.txt Optimization', category: 'technical', subcategory: 'Crawling', description: 'Configure robots.txt to allow indexing of important pages and block irrelevant ones.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Canonical Tags on All Pages', category: 'technical', subcategory: 'Crawling', description: 'Prevent duplicate content issues with self-referencing canonical tags.', priority: 'critical', automation_frequency: 'one_time', automation_capable: true, impact_score: 9, difficulty: 'easy', google_confirmed: true },
      { method_name: 'HTTPS/SSL Enforcement', category: 'technical', subcategory: 'Security', description: 'Force HTTPS with auto-renewing SSL certificates. Google confirms HTTPS is a ranking signal.', priority: 'critical', automation_frequency: 'one_time', automation_capable: true, impact_score: 8, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Core Web Vitals — LCP < 2.5s', category: 'technical', subcategory: 'Page Experience', description: 'Optimize Largest Contentful Paint. Google confirmed ranking factor.', priority: 'critical', automation_frequency: 'ongoing', automation_capable: true, impact_score: 9, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Core Web Vitals — CLS < 0.1', category: 'technical', subcategory: 'Page Experience', description: 'Minimize Cumulative Layout Shift. Google confirmed ranking factor.', priority: 'critical', automation_frequency: 'ongoing', automation_capable: true, impact_score: 9, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Core Web Vitals — INP < 200ms', category: 'technical', subcategory: 'Page Experience', description: 'Optimize Interaction to Next Paint (replaced FID in 2024).', priority: 'critical', automation_frequency: 'ongoing', automation_capable: true, impact_score: 9, difficulty: 'hard', google_confirmed: true },
      { method_name: 'Mobile-First Responsive Design', category: 'technical', subcategory: 'Mobile', description: 'Google uses mobile-first indexing. Site must be fully responsive.', priority: 'critical', automation_frequency: 'one_time', automation_capable: true, impact_score: 10, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Page Speed — Image Optimization', category: 'technical', subcategory: 'Performance', description: 'Compress images, use WebP/AVIF, responsive srcset, lazy loading.', priority: 'high', automation_frequency: 'ongoing', automation_capable: true, impact_score: 8, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Page Speed — JS/CSS Minification', category: 'technical', subcategory: 'Performance', description: 'Minify and tree-shake JavaScript and CSS bundles.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'CDN Setup (Edge Network)', category: 'technical', subcategory: 'Performance', description: 'Serve assets via CDN (Vercel Edge, Cloudflare) for global low latency.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: false },
      { method_name: 'GZIP/Brotli Compression', category: 'technical', subcategory: 'Performance', description: 'Enable Brotli/GZIP compression for all text-based responses.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 6, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Lazy Loading (Images, Iframes)', category: 'technical', subcategory: 'Performance', description: 'Defer offscreen images and iframes until needed.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 6, difficulty: 'easy', google_confirmed: true },
      { method_name: '301 Redirect Management', category: 'technical', subcategory: 'Crawling', description: 'Redirect old URLs to new ones to preserve link equity.', priority: 'high', automation_frequency: 'ongoing', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: '404 Error Monitoring', category: 'technical', subcategory: 'Crawling', description: 'Monitor for 404s and fix broken links daily.', priority: 'medium', automation_frequency: 'daily', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'BreadcrumbList Schema', category: 'technical', subcategory: 'Schema', description: 'Add BreadcrumbList JSON-LD for rich result breadcrumbs.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Organization Schema', category: 'technical', subcategory: 'Schema', description: 'Add Organization JSON-LD for knowledge panel eligibility.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'LocalBusiness Schema', category: 'technical', subcategory: 'Schema', description: 'Add LocalBusiness JSON-LD with NAP, hours, geo coordinates.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 8, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Product Schema', category: 'technical', subcategory: 'Schema', description: 'Add Product JSON-LD for product rich results.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 6, difficulty: 'easy', google_confirmed: true },
      { method_name: 'FAQ Schema', category: 'technical', subcategory: 'Schema', description: 'Add FAQPage JSON-LD for FAQ rich results.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 8, difficulty: 'easy', google_confirmed: true },
      { method_name: 'HowTo Schema', category: 'technical', subcategory: 'Schema', description: 'Add HowTo JSON-LD for how-to rich results.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 6, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Review/AggregateRating Schema', category: 'technical', subcategory: 'Schema', description: 'Add Review schema for star ratings in SERPs.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Article/BlogPosting Schema', category: 'technical', subcategory: 'Schema', description: 'Add Article JSON-LD for content pages.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'VideoObject Schema', category: 'technical', subcategory: 'Schema', description: 'Add VideoObject JSON-LD for video rich results.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 6, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Service Schema', category: 'technical', subcategory: 'Schema', description: 'Add Service JSON-LD for service-based businesses.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 6, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Open Graph Tags', category: 'technical', subcategory: 'Social Meta', description: 'Add OG tags for social sharing previews.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Twitter Card Tags', category: 'technical', subcategory: 'Social Meta', description: 'Add Twitter Card meta tags for Twitter sharing.', priority: 'low', automation_frequency: 'one_time', automation_capable: true, impact_score: 4, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Hreflang Tags (International)', category: 'technical', subcategory: 'International', description: 'Add hreflang tags for multi-language/multi-region sites.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 6, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Structured Data Validation', category: 'technical', subcategory: 'Schema', description: 'Validate all schema with Google Rich Results Test weekly.', priority: 'high', automation_frequency: 'weekly', automation_capable: true, impact_score: 6, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Semantic HTML Structure', category: 'technical', subcategory: 'Structure', description: 'Use proper HTML5 semantic elements (article, section, nav, header, footer).', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'WCAG Accessibility Compliance', category: 'technical', subcategory: 'Accessibility', description: 'Meet WCAG 2.1 AA standards. Accessibility is a ranking consideration.', priority: 'medium', automation_frequency: 'one_time', automation_capable: false, impact_score: 5, difficulty: 'medium', google_confirmed: false },

      // ===== INDEXING =====
      { method_name: 'GSC Property Setup + Verification', category: 'indexing', subcategory: 'Google', description: 'Add and verify every domain in Google Search Console.', priority: 'critical', automation_frequency: 'one_time', automation_capable: true, function_name: 'bulkSubmitGSC', impact_score: 10, difficulty: 'medium', google_confirmed: true },
      { method_name: 'GSC Sitemap Submission', category: 'indexing', subcategory: 'Google', description: 'Submit sitemap.xml to GSC for every property.', priority: 'critical', automation_frequency: 'one_time', automation_capable: true, function_name: 'submitToGSC', impact_score: 9, difficulty: 'easy', google_confirmed: true },
      { method_name: 'GSC URL Inspection + Request Indexing', category: 'indexing', subcategory: 'Google', description: 'Use URL Inspection API to request indexing of new/updated pages.', priority: 'high', automation_frequency: 'daily', automation_capable: true, function_name: 'submitToGSC', impact_score: 8, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Google Indexing API', category: 'indexing', subcategory: 'Google', description: 'Use Google Indexing API to notify Google of new/updated pages instantly.', priority: 'high', automation_frequency: 'daily', automation_capable: true, impact_score: 8, difficulty: 'medium', google_confirmed: true },
      { method_name: 'IndexNow API (Bing/Yandex)', category: 'indexing', subcategory: 'Bing', description: 'Ping IndexNow API for instant Bing/Yandex indexing (minutes, not days).', priority: 'high', automation_frequency: 'daily', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Bing Webmaster Tools Submission', category: 'indexing', subcategory: 'Bing', description: 'Submit site + sitemap to Bing Webmaster Tools.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'RSS Feed Creation + Submission', category: 'indexing', subcategory: 'Syndication', description: 'Create RSS feed and submit to feed aggregators.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Sitemap Auto-Ping on Content Changes', category: 'indexing', subcategory: 'Automation', description: 'Automatically ping search engines when sitemap updates.', priority: 'high', automation_frequency: 'ongoing', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Google Publisher Center (News)', category: 'indexing', subcategory: 'Google', description: 'Submit to Google Publisher Center for Google News inclusion.', priority: 'low', automation_frequency: 'one_time', automation_capable: false, impact_score: 4, difficulty: 'medium', google_confirmed: true },

      // ===== CONTENT =====
      { method_name: 'Keyword Research + Mapping', category: 'content', subcategory: 'Strategy', description: 'Research keywords with volume/difficulty data and map to pages.', priority: 'critical', automation_frequency: 'monthly', automation_capable: true, function_name: 'runRankEngine', impact_score: 10, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Search Intent Analysis', category: 'content', subcategory: 'Strategy', description: 'Classify keywords by intent (transactional, commercial, informational, navigational).', priority: 'high', automation_frequency: 'monthly', automation_capable: true, impact_score: 8, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Topic Cluster Creation (Pillar + Supporting)', category: 'content', subcategory: 'Strategy', description: 'Create pillar pages + 10-20 supporting cluster pages with internal links.', priority: 'critical', automation_frequency: 'one_time', automation_capable: true, function_name: 'runRankEngine', impact_score: 9, difficulty: 'hard', google_confirmed: true },
      { method_name: 'Content Gap Analysis vs Competitors', category: 'content', subcategory: 'Strategy', description: 'Find topics competitors rank for that you do not. Fill gaps with new content.', priority: 'high', automation_frequency: 'weekly', automation_capable: true, function_name: 'analyzeCompetitorGaps', impact_score: 8, difficulty: 'medium', google_confirmed: true },
      { method_name: 'LSI Keyword Integration', category: 'content', subcategory: 'Optimization', description: 'Include Latent Semantic Indexing keywords for topical relevance.', priority: 'medium', automation_frequency: 'ongoing', automation_capable: true, impact_score: 6, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Entity-Based Content Optimization', category: 'content', subcategory: 'Optimization', description: 'Optimize for entities and topics, not just keywords. Google uses entity recognition.', priority: 'high', automation_frequency: 'ongoing', automation_capable: true, impact_score: 8, difficulty: 'hard', google_confirmed: true },
      { method_name: 'Content Freshness (Regular Updates)', category: 'content', subcategory: 'Maintenance', description: 'Update existing content regularly. Freshness is a ranking factor.', priority: 'high', automation_frequency: 'weekly', automation_capable: true, function_name: 'refreshStaleContent', impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Content Depth (2000+ Words for Competitive Keywords)', category: 'content', subcategory: 'Quality', description: 'Comprehensive content outperforms thin content for competitive terms.', priority: 'high', automation_frequency: 'ongoing', automation_capable: true, function_name: 'runRankEngine', impact_score: 8, difficulty: 'medium', google_confirmed: true },
      { method_name: 'FAQ Section Generation', category: 'content', subcategory: 'Structure', description: 'Generate FAQ sections with FAQ schema for every service page.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, function_name: 'runRankEngine', impact_score: 8, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Image Alt Text Optimization', category: 'content', subcategory: 'Optimization', description: 'Write descriptive, keyword-relevant alt text for all images.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Video Content Creation', category: 'content', subcategory: 'Media', description: 'Create video content with VideoObject schema. Video results drive traffic.', priority: 'medium', automation_frequency: 'ongoing', automation_capable: true, impact_score: 6, difficulty: 'hard', google_confirmed: true },
      { method_name: 'Content Silo Structure', category: 'content', subcategory: 'Structure', description: 'Organize content into topical silos with clear hierarchy.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'medium', google_confirmed: true },
      { method_name: 'AI Content Generation (with Human Review)', category: 'content', subcategory: 'Production', description: 'Generate SEO-optimized content at scale with AI, reviewed by humans.', priority: 'high', automation_frequency: 'ongoing', automation_capable: true, function_name: 'runRankEngine', impact_score: 8, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Readability Optimization', category: 'content', subcategory: 'Quality', description: 'Optimize Flesch reading score. Content should be easy to read.', priority: 'medium', automation_frequency: 'ongoing', automation_capable: true, impact_score: 4, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Plagiarism Checking', category: 'content', subcategory: 'Quality', description: 'Ensure all content is original. Copied content is penalized.', priority: 'medium', automation_frequency: 'ongoing', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: true },

      // ===== ON-PAGE SEO =====
      { method_name: 'Title Tag Optimization (50-60 chars)', category: 'on_page', subcategory: 'Meta', description: 'Write compelling title tags with primary keyword near the start.', priority: 'critical', automation_frequency: 'one_time', automation_capable: true, impact_score: 9, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Meta Description (150-160 chars)', category: 'on_page', subcategory: 'Meta', description: 'Write compelling meta descriptions that improve CTR.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'H1 Tag Optimization', category: 'on_page', subcategory: 'Headings', description: 'One H1 per page with primary keyword.', priority: 'critical', automation_frequency: 'one_time', automation_capable: true, impact_score: 8, difficulty: 'easy', google_confirmed: true },
      { method_name: 'H2-H6 Heading Structure', category: 'on_page', subcategory: 'Headings', description: 'Logical heading hierarchy with secondary keywords.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Keyword Density (1-2%)', category: 'on_page', subcategory: 'Optimization', description: 'Maintain natural keyword density. Avoid keyword stuffing.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'URL Structure (Short, Keyword-Rich)', category: 'on_page', subcategory: 'URL', description: 'Short, descriptive URLs with target keyword, hyphens as separators.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Internal Linking Strategy', category: 'on_page', subcategory: 'Linking', description: 'Strategic internal links between related pages to distribute authority.', priority: 'critical', automation_frequency: 'ongoing', automation_capable: true, impact_score: 9, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Internal Link Anchor Text Optimization', category: 'on_page', subcategory: 'Linking', description: 'Use descriptive, keyword-relevant anchor text for internal links.', priority: 'high', automation_frequency: 'ongoing', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Breadcrumb Navigation', category: 'on_page', subcategory: 'Navigation', description: 'Add breadcrumb navigation with schema for UX and SEO.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Image Optimization (Size, Format, Naming)', category: 'on_page', subcategory: 'Images', description: 'Compress images, use modern formats, name files with keywords.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Table of Contents', category: 'on_page', subcategory: 'Structure', description: 'Add TOC for long content. Improves UX and earns jump links in SERPs.', priority: 'low', automation_frequency: 'one_time', automation_capable: true, impact_score: 4, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Author Bio + E-E-A-T Signals', category: 'on_page', subcategory: 'Trust', description: 'Add author bios with credentials for E-E-A-T signals.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Trust Badges + Certifications', category: 'on_page', subcategory: 'Trust', description: 'Display trust signals (SSL, BBB, certifications, awards).', priority: 'low', automation_frequency: 'one_time', automation_capable: false, impact_score: 4, difficulty: 'easy', google_confirmed: false },
      { method_name: 'NAP Consistency (Name, Address, Phone)', category: 'on_page', subcategory: 'Local', description: 'Consistent NAP across all pages. Critical for local SEO.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 8, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Privacy Policy + Terms of Service', category: 'on_page', subcategory: 'Legal', description: 'Required for Google Trust. Google checks for these pages.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 4, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Social Sharing Buttons', category: 'on_page', subcategory: 'Social', description: 'Add social sharing buttons to encourage sharing.', priority: 'low', automation_frequency: 'one_time', automation_capable: true, impact_score: 3, difficulty: 'easy', google_confirmed: false },

      // ===== OFF-PAGE SEO =====
      { method_name: 'Backlink Prospecting (Competitor Analysis)', category: 'off_page', subcategory: 'Link Building', description: 'Find backlink prospects by analyzing competitor backlinks.', priority: 'critical', automation_frequency: 'weekly', automation_capable: true, function_name: 'prospectBacklinks', impact_score: 10, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Backlink Outreach (Email Campaigns)', category: 'off_page', subcategory: 'Link Building', description: 'Send personalized outreach emails to acquire backlinks.', priority: 'critical', automation_frequency: 'weekly', automation_capable: true, function_name: 'sendOutreach', impact_score: 10, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Guest Post Pitching', category: 'off_page', subcategory: 'Link Building', description: 'Pitch guest post ideas to relevant blogs for author bio backlinks.', priority: 'high', automation_frequency: 'ongoing', automation_capable: true, function_name: 'sendOutreach', impact_score: 8, difficulty: 'hard', google_confirmed: true },
      { method_name: 'Resource Page Link Building', category: 'off_page', subcategory: 'Link Building', description: 'Get links from resource pages by offering valuable content.', priority: 'high', automation_frequency: 'ongoing', automation_capable: true, function_name: 'sendOutreach', impact_score: 7, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Broken Link Building', category: 'off_page', subcategory: 'Link Building', description: 'Find broken links on other sites and offer your content as replacement.', priority: 'high', automation_frequency: 'ongoing', automation_capable: true, impact_score: 7, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Skyscraper Technique', category: 'off_page', subcategory: 'Link Building', description: 'Create better content than top-ranking pages and outreach to their linkers.', priority: 'high', automation_frequency: 'ongoing', automation_capable: true, impact_score: 7, difficulty: 'hard', google_confirmed: true },
      { method_name: 'Tier 2 Link Building', category: 'off_page', subcategory: 'Tiered Links', description: 'Build backlinks to your backlinks to multiply authority.', priority: 'medium', automation_frequency: 'weekly', automation_capable: true, impact_score: 6, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Tier 3 Link Building', category: 'off_page', subcategory: 'Tiered Links', description: 'Build links to your tier 2 links for compounding authority.', priority: 'low', automation_frequency: 'weekly', automation_capable: true, impact_score: 4, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Web 2.0 Link Building (WordPress, Medium)', category: 'off_page', subcategory: 'Content Syndication', description: 'Create content on Web 2.0 properties with backlinks to your site.', priority: 'medium', automation_frequency: 'weekly', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Social Bookmarking (Reddit, Mix)', category: 'off_page', subcategory: 'Content Syndication', description: 'Submit content to social bookmarking sites for links + traffic.', priority: 'low', automation_frequency: 'weekly', automation_capable: true, impact_score: 3, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Forum Link Building (Quora)', category: 'off_page', subcategory: 'Content Syndication', description: 'Answer questions on Quora and niche forums with relevant links.', priority: 'medium', automation_frequency: 'ongoing', automation_capable: true, impact_score: 5, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Profile Link Building', category: 'off_page', subcategory: 'Link Building', description: 'Create profiles on relevant platforms with backlinks.', priority: 'low', automation_frequency: 'one_time', automation_capable: true, impact_score: 3, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Directory Submission (General + Niche)', category: 'off_page', subcategory: 'Citations', description: 'Submit to quality directories. Avoid low-quality spam directories.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, function_name: 'buildCitationPlan', impact_score: 5, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Press Release Distribution', category: 'off_page', subcategory: 'PR', description: 'Distribute press releases for news-worthy content + backlinks.', priority: 'high', automation_frequency: 'monthly', automation_capable: true, impact_score: 7, difficulty: 'medium', google_confirmed: true },
      { method_name: 'HARO / Connectively Response', category: 'off_page', subcategory: 'PR', description: 'Respond to journalist queries for authoritative backlinks (DA 80+).', priority: 'high', automation_frequency: 'daily', automation_capable: true, impact_score: 9, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Podcast Guest Outreach', category: 'off_page', subcategory: 'PR', description: 'Get featured on podcasts for backlinks + brand exposure.', priority: 'medium', automation_frequency: 'ongoing', automation_capable: false, impact_score: 6, difficulty: 'hard', google_confirmed: false },
      { method_name: 'Expert Roundups', category: 'off_page', subcategory: 'Content Syndication', description: 'Create expert roundup posts and notify participants for backlinks.', priority: 'medium', automation_frequency: 'monthly', automation_capable: true, impact_score: 5, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Infographic Submission', category: 'off_page', subcategory: 'Content Syndication', description: 'Create and submit infographics to infographic directories.', priority: 'low', automation_frequency: 'monthly', automation_capable: true, impact_score: 4, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Video Backlinks (YouTube)', category: 'off_page', subcategory: 'Content Syndication', description: 'Create YouTube videos with backlinks in descriptions.', priority: 'medium', automation_frequency: 'ongoing', automation_capable: true, impact_score: 5, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Document Sharing (SlideShare)', category: 'off_page', subcategory: 'Content Syndication', description: 'Upload presentations/documents with backlinks to SlideShare, Google Docs.', priority: 'low', automation_frequency: 'monthly', automation_capable: true, impact_score: 4, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Unlinked Brand Mention Reclamation', category: 'off_page', subcategory: 'Link Building', description: 'Find unlinked brand mentions and request a link.', priority: 'high', automation_frequency: 'weekly', automation_capable: true, impact_score: 7, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Competitor Backlink Replication', category: 'off_page', subcategory: 'Link Building', description: 'Find sites linking to competitors and get them to link to you too.', priority: 'high', automation_frequency: 'weekly', automation_capable: true, function_name: 'prospectBacklinks', impact_score: 8, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Scholarship Link Building (.edu)', category: 'off_page', subcategory: 'Link Building', description: 'Offer a scholarship for .edu backlinks. High authority links.', priority: 'medium', automation_frequency: 'one_time', automation_capable: false, impact_score: 7, difficulty: 'hard', google_confirmed: true },
      { method_name: 'Sponsorship Links', category: 'off_page', subcategory: 'Link Building', description: 'Sponsor events/organizations for backlinks from their sites.', priority: 'low', automation_frequency: 'one_time', automation_capable: false, impact_score: 5, difficulty: 'medium', google_confirmed: false },

      // ===== LOCAL SEO =====
      { method_name: 'Google Business Profile Creation + Optimization', category: 'local', subcategory: 'GBP', description: 'Create and fully optimize GBP. #1 local ranking factor.', priority: 'critical', automation_frequency: 'one_time', automation_capable: false, impact_score: 10, difficulty: 'easy', google_confirmed: true },
      { method_name: 'GBP Post Automation (Weekly)', category: 'local', subcategory: 'GBP', description: 'Post weekly updates to Google Business Profile.', priority: 'high', automation_frequency: 'weekly', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'GBP Q&A Management', category: 'local', subcategory: 'GBP', description: 'Monitor and respond to GBP Q&A. Seed common questions.', priority: 'medium', automation_frequency: 'ongoing', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: true },
      { method_name: 'GBP Photo Uploads', category: 'local', subcategory: 'GBP', description: 'Upload new photos weekly to GBP. Active profiles rank higher.', priority: 'medium', automation_frequency: 'weekly', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: true },
      { method_name: 'GBP Review Responses', category: 'local', subcategory: 'GBP', description: 'Respond to all GBP reviews. Shows active management.', priority: 'high', automation_frequency: 'daily', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'GBP Product/Services Catalog', category: 'local', subcategory: 'GBP', description: 'Add products and services to GBP listing.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: true },
      { method_name: 'NAP Consistency Audit', category: 'local', subcategory: 'Citations', description: 'Audit NAP consistency across all citations monthly.', priority: 'critical', automation_frequency: 'monthly', automation_capable: true, impact_score: 8, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Local Citation Building', category: 'local', subcategory: 'Citations', description: 'Build citations on Yelp, BBB, Angi, Apple Maps, etc.', priority: 'critical', automation_frequency: 'one_time', automation_capable: true, function_name: 'buildCitationPlan', impact_score: 9, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Local Citation Auditing (NAP)', category: 'local', subcategory: 'Citations', description: 'Check for duplicate/inconsistent citations and fix them.', priority: 'high', automation_frequency: 'monthly', automation_capable: true, impact_score: 6, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Review Generation Campaigns (SMS/Email)', category: 'local', subcategory: 'Reviews', description: 'Automated SMS/email campaigns to collect Google reviews. Reviews are top 3 local ranking factor.', priority: 'critical', automation_frequency: 'ongoing', automation_capable: true, impact_score: 10, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Review Monitoring + Response', category: 'local', subcategory: 'Reviews', description: 'Monitor reviews across all platforms and respond daily.', priority: 'high', automation_frequency: 'daily', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Local Landing Pages (City + Service)', category: 'local', subcategory: 'Pages', description: 'Create dedicated landing pages for each city + service combination.', priority: 'critical', automation_frequency: 'one_time', automation_capable: true, function_name: 'runRankEngine', impact_score: 10, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Geo-Targeted Content', category: 'local', subcategory: 'Content', description: 'Include city/region-specific content, landmarks, local references.', priority: 'high', automation_frequency: 'ongoing', automation_capable: true, impact_score: 7, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Local Schema Markup', category: 'local', subcategory: 'Schema', description: 'Add LocalBusiness schema with geo coordinates, service area.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 8, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Apple Maps Listing', category: 'local', subcategory: 'Citations', description: 'Create Apple Maps listing for local visibility.', priority: 'medium', automation_frequency: 'one_time', automation_capable: false, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Bing Places for Business', category: 'local', subcategory: 'Citations', description: 'Create Bing Places listing for Bing local results.', priority: 'medium', automation_frequency: 'one_time', automation_capable: false, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Industry-Specific Directories', category: 'local', subcategory: 'Citations', description: 'Submit to niche-specific directories (e.g. Houzz for home services).', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, function_name: 'buildCitationPlan', impact_score: 6, difficulty: 'easy', google_confirmed: true },

      // ===== SOCIAL SIGNALS =====
      { method_name: 'Social Profile Creation + Optimization', category: 'social', subcategory: 'Profiles', description: 'Create and optimize profiles on Facebook, Twitter, LinkedIn, Instagram.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Automated Social Posting (FB, Twitter, LinkedIn)', category: 'social', subcategory: 'Posting', description: 'Auto-post content to social platforms daily.', priority: 'medium', automation_frequency: 'daily', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Pinterest Pin Creation', category: 'social', subcategory: 'Posting', description: 'Create and pin images with backlinks to Pinterest.', priority: 'low', automation_frequency: 'weekly', automation_capable: true, impact_score: 4, difficulty: 'easy', google_confirmed: false },
      { method_name: 'YouTube Video Creation + Optimization', category: 'social', subcategory: 'Video', description: 'Create YouTube videos with optimized titles, descriptions, tags.', priority: 'high', automation_frequency: 'weekly', automation_capable: true, impact_score: 7, difficulty: 'hard', google_confirmed: true },
      { method_name: 'TikTok Content', category: 'social', subcategory: 'Video', description: 'Create TikTok content for brand awareness + social signals.', priority: 'low', automation_frequency: 'weekly', automation_capable: true, impact_score: 4, difficulty: 'hard', google_confirmed: false },
      { method_name: 'Social Sharing Automation', category: 'social', subcategory: 'Posting', description: 'Auto-share new content across all social platforms.', priority: 'low', automation_frequency: 'ongoing', automation_capable: true, impact_score: 3, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Brand Mention Monitoring (Social)', category: 'social', subcategory: 'Monitoring', description: 'Monitor social media for brand mentions and engage.', priority: 'medium', automation_frequency: 'daily', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Influencer Outreach', category: 'social', subcategory: 'Outreach', description: 'Partner with influencers for backlinks + social signals.', priority: 'medium', automation_frequency: 'monthly', automation_capable: false, impact_score: 6, difficulty: 'hard', google_confirmed: false },

      // ===== AUTHORITY + TRUST (E-E-A-T) =====
      { method_name: 'Author Pages with Credentials', category: 'authority', subcategory: 'E-E-A-T', description: 'Create detailed author pages with credentials, expertise, photos.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Author Schema Markup', category: 'authority', subcategory: 'E-E-A-T', description: 'Add Person schema with author credentials, sameAs links.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 6, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Expert Quotes + Citations', category: 'authority', subcategory: 'E-E-A-T', description: 'Include quotes from experts and cite authoritative sources.', priority: 'medium', automation_frequency: 'ongoing', automation_capable: true, impact_score: 6, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Case Studies', category: 'authority', subcategory: 'Content', description: 'Publish case studies with real data. Builds trust + authority.', priority: 'high', automation_frequency: 'monthly', automation_capable: true, impact_score: 7, difficulty: 'hard', google_confirmed: true },
      { method_name: 'Original Research + Surveys', category: 'authority', subcategory: 'Content', description: 'Conduct original research. Gets cited and linked to naturally.', priority: 'high', automation_frequency: 'monthly', automation_capable: false, impact_score: 8, difficulty: 'hard', google_confirmed: true },
      { method_name: 'Awards + Recognition', category: 'authority', subcategory: 'Trust', description: 'Display awards and recognition badges for trust signals.', priority: 'low', automation_frequency: 'one_time', automation_capable: false, impact_score: 4, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Trust Signals (SSL, Badges, Security)', category: 'authority', subcategory: 'Trust', description: 'Display trust badges, security certificates, privacy seals.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 4, difficulty: 'easy', google_confirmed: false },
      { method_name: 'About Page Optimization', category: 'authority', subcategory: 'Trust', description: 'Comprehensive About page with company history, team, mission.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Contact Page with Real Info', category: 'authority', subcategory: 'Trust', description: 'Real contact info: phone, email, address, map. Google checks this.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 6, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Editorial Policy', category: 'authority', subcategory: 'Trust', description: 'Publish editorial policy for content quality standards.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 4, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Fact-Checking + Sources', category: 'authority', subcategory: 'E-E-A-T', description: 'Cite sources for claims. Google values factual accuracy.', priority: 'medium', automation_frequency: 'ongoing', automation_capable: true, impact_score: 5, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Wikipedia Page (if notable)', category: 'authority', subcategory: 'Knowledge', description: 'Create Wikipedia page for brand entity. High authority link.', priority: 'low', automation_frequency: 'one_time', automation_capable: false, impact_score: 7, difficulty: 'hard', google_confirmed: false },
      { method_name: 'Knowledge Panel Optimization', category: 'authority', subcategory: 'Knowledge', description: 'Optimize for Google Knowledge Panel via Wikidata + schema.', priority: 'medium', automation_frequency: 'ongoing', automation_capable: true, impact_score: 6, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Brand Entity Building (Wikidata)', category: 'authority', subcategory: 'Knowledge', description: 'Create Wikidata entity for brand. Helps Google understand your entity.', priority: 'medium', automation_frequency: 'one_time', automation_capable: true, impact_score: 6, difficulty: 'medium', google_confirmed: true },

      // ===== MONITORING + ANALYTICS =====
      { method_name: 'Daily Rank Tracking', category: 'monitoring', subcategory: 'Rankings', description: 'Track keyword positions daily. Detect drops early.', priority: 'critical', automation_frequency: 'daily', automation_capable: true, function_name: 'syncRankings', impact_score: 9, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Daily GSC Data Sync', category: 'monitoring', subcategory: 'Analytics', description: 'Sync Google Search Console data daily for impressions, clicks, CTR.', priority: 'critical', automation_frequency: 'daily', automation_capable: true, function_name: 'syncRankings', impact_score: 9, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Google Analytics Tracking', category: 'monitoring', subcategory: 'Analytics', description: 'Install GA4 for traffic analysis, conversion tracking.', priority: 'high', automation_frequency: 'one_time', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Backlink Monitoring (New/Lost)', category: 'monitoring', subcategory: 'Links', description: 'Monitor for new and lost backlinks weekly.', priority: 'high', automation_frequency: 'weekly', automation_capable: true, impact_score: 7, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Competitor Rank Monitoring', category: 'monitoring', subcategory: 'Competitors', description: 'Track competitor keyword rankings daily.', priority: 'high', automation_frequency: 'daily', automation_capable: true, impact_score: 7, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Competitor Backlink Monitoring', category: 'monitoring', subcategory: 'Competitors', description: 'Monitor competitor new backlinks weekly. Replicate opportunities.', priority: 'high', automation_frequency: 'weekly', automation_capable: true, impact_score: 7, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Competitor Content Monitoring', category: 'monitoring', subcategory: 'Competitors', description: 'Monitor competitor content changes and new pages.', priority: 'medium', automation_frequency: 'weekly', automation_capable: true, impact_score: 5, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Technical SEO Monitoring (Uptime, Broken Links)', category: 'monitoring', subcategory: 'Technical', description: 'Daily monitoring of uptime, broken links, crawl errors.', priority: 'high', automation_frequency: 'daily', automation_capable: true, function_name: 'runTechnicalSeoAudit', impact_score: 7, difficulty: 'easy', google_confirmed: true },
      { method_name: 'Core Web Vitals Monitoring', category: 'monitoring', subcategory: 'Technical', description: 'Weekly CWV monitoring via PageSpeed Insights API.', priority: 'high', automation_frequency: 'weekly', automation_capable: true, impact_score: 7, difficulty: 'medium', google_confirmed: true },
      { method_name: 'Brand Mention Monitoring', category: 'monitoring', subcategory: 'Brand', description: 'Monitor web for brand mentions. Reclaim unlinked mentions.', priority: 'medium', automation_frequency: 'daily', automation_capable: true, impact_score: 5, difficulty: 'easy', google_confirmed: false },
      { method_name: 'Review Monitoring', category: 'monitoring', subcategory: 'Reviews', description: 'Monitor reviews across Google, Yelp, BBB. Respond daily.', priority: 'high', automation_frequency: 'daily', automation_capable: true, impact_score: 6, difficulty: 'easy', google_confirmed: true },
      { method_name: 'SERP Feature Tracking (Featured Snippets, PAA)', category: 'monitoring', subcategory: 'SERP', description: 'Track SERP features: featured snippets, People Also Ask, local pack.', priority: 'high', automation_frequency: 'weekly', automation_capable: true, impact_score: 7, difficulty: 'medium', google_confirmed: true },
      { method_name: 'CTR Optimization', category: 'monitoring', subcategory: 'Optimization', description: 'Analyze and optimize click-through rates from SERPs.', priority: 'high', automation_frequency: 'monthly', automation_capable: true, impact_score: 7, difficulty: 'medium', google_confirmed: true },
      { method_name: 'A/B Testing (Titles, Meta Descriptions)', category: 'monitoring', subcategory: 'Optimization', description: 'Test different titles and meta descriptions to improve CTR.', priority: 'medium', automation_frequency: 'ongoing', automation_capable: true, impact_score: 5, difficulty: 'medium', google_confirmed: false },
      { method_name: 'Search Intent Shift Detection', category: 'monitoring', subcategory: 'SERP', description: 'Detect when search intent shifts for tracked keywords.', priority: 'medium', automation_frequency: 'monthly', automation_capable: true, impact_score: 5, difficulty: 'hard', google_confirmed: true },
    ];

    await svc.entities.SeoStandardChecklist.bulkCreate(methods);

    return Response.json({
      ok: true,
      message: `Seeded ${methods.length} SEO methods`,
      count: methods.length,
      categories: [...new Set(methods.map(m => m.category))],
    });
  } catch (error) {
    return Response.json({ error: error.message, stack: error.stack }, { status: 500 });
  }
}