// Product catalog data for the backend seed function.
// This is the server-side source of truth for all products/services.
// The frontend has its own copy in src/lib/serviceCatalog.js for rendering,
// but this module feeds the ServiceCatalogEntry entity with full SEO/AEO/org metadata.

export const SERVICE_CATALOG_DATA = [
  // ─── GROWTH PACKAGES ──────────────────────────────────────
  {
    product_id: "elite-monthly",
    name: "Elite Growth Package",
    category: "package",
    tagline: "Done-for-you growth engine — brand, web, ranking & reporting (one-time)",
    description: "The complete growth package — 100% digital deliverables. Custom logo, full brand identity, built-to-order website, SEO/AEO optimization, rank engine, citations, backlinks and reporting. Pay once, get everything.",
    price: 2999, price_label: "$2,999 one-time", delivery_time: "7 days",
    features: [
      "Multiple markets / sites included",
      "Priority execution (jump the queue)",
      "Dedicated support & project lead",
      "Onboarding & business profile intake (per market)",
      "Logo Generator — 10 concepts per market, pick 1",
      "Brand Generator — 10 mockups per market, pick up to 3",
      "Website Design — 10 packs per market, pick up to 3",
      "Website build per market (design, copy, imagery)",
      "On-page SEO + AEO optimization per site",
      "JSON-LD structured data per site",
      "Rank Engine — pages, citations & backlinks per market",
      "Clone & deploy portfolio sites end-to-end",
      "GSC sync, indexing & traffic tracking",
      "Backlink outreach at scale",
      "Ongoing content refresh & optimization",
      "Lead capture wiring per site",
      "Monthly execution & priority reporting",
      "Priority portal access",
      "All tools unlocked",
    ],
    deliverables: ["Monthly execution", "Priority portal", "Live site URLs", "Ranking & traffic reports", "Dedicated project lead"],
    seo_metadata: { meta_title: "Elite Growth Package — Full Done-For-You SEO & Lead Gen", meta_description: "Complete growth package: custom logo, brand, website, SEO/AEO, rank engine, citations, backlinks & reporting. One-time payment.", keywords: ["local seo", "lead generation", "website design", "brand identity", "rank engine", "citations", "backlinks"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["The Elite Growth Package is a one-time, done-for-you service that includes custom logo design, brand identity, a conversion-optimized website, SEO/AEO optimization, autonomous rank engine, local citations, backlink outreach, and monthly reporting across multiple markets."], entity_types: ["Service", "Product"], topic_clusters: ["local seo", "brand identity", "website design", "ai search optimization", "lead generation"], llm_summary: "Elite Growth Package: one-time, full-service local business growth — brand, website, SEO, AEO, citations, backlinks, and ranking engine across multiple markets." },
    organizational_metadata: { tier: "elite", tags: ["package", "premium", "multi-market", "done-for-you"], related_services: ["monthly-seo-rank", "monthly-citations", "monthly-backlinks", "monthly-content"], automation_function: "pushAllToMax", pipeline_stage: "full-build" },
    statistics: [{ label: "Avg. lead increase", value: "3.2×" }, { label: "Time to page one", value: "60–90 days" }, { label: "Markets included", value: "Multiple" }, { label: "Payment", value: "One-time" }],
  },
  {
    product_id: "pro-monthly",
    name: "Pro Growth Package",
    category: "package",
    tagline: "Full-service brand, website & ranking for one market (one-time)",
    description: "Everything you need to launch and grow a single local site — brand kit, website build, SEO/AEO, rank engine, and reporting. Pay once, get everything.",
    price: 999, price_label: "$999 one-time", delivery_time: "7 days",
    features: [
      "1 market / site included",
      "Onboarding & business profile intake",
      "Logo Generator — 10 concepts, pick 1",
      "Brand Generator — 10 mockups, pick up to 3",
      "Website Design — 10 packs, pick up to 3",
      "Website build (design, copy, imagery)",
      "On-page SEO + AEO optimization",
      "JSON-LD structured data",
      "Rank Engine — SEO pages, citations & backlinks",
      "GSC sync & indexing",
      "Backlink outreach",
      "Lead capture wiring",
    ],
    deliverables: ["Monthly execution", "Portal access", "Live site URL", "Ranking & traffic reports"],
    seo_metadata: { meta_title: "Pro Growth Package — Brand, Website & SEO for One Market", meta_description: "Full-service brand kit, website build, SEO/AEO, rank engine, and reporting for one local market. One-time payment.", keywords: ["local seo", "website design", "brand identity", "rank engine", "lead generation"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["The Pro Growth Package is a one-time, done-for-you service for a single local market that includes brand identity, website design and build, SEO/AEO optimization, JSON-LD structured data, rank engine, GSC sync, backlink outreach, and lead capture."], entity_types: ["Service", "Product"], topic_clusters: ["local seo", "brand identity", "website design", "ai search optimization"], llm_summary: "Pro Growth Package: one-time, full-service local business growth for a single market — brand, website, SEO, AEO, and ranking engine." },
    organizational_metadata: { tier: "pro", tags: ["package", "single-market", "done-for-you"], related_services: ["monthly-seo-rank", "monthly-citations", "monthly-content"], automation_function: "runRankEngine", pipeline_stage: "full-build" },
    statistics: [{ label: "Avg. lead increase", value: "2.1×" }, { label: "Time to page one", value: "90–120 days" }, { label: "Markets included", value: "1" }, { label: "Payment", value: "One-time" }],
  },

  // ─── MONTHLY SERVICES ────────────────────────────────────
  {
    product_id: "monthly-seo-rank",
    name: "SEO Rank & Report",
    category: "monthly-service",
    tagline: "Monthly SEO page generation, ranking tracking & reports",
    description: "Autonomous rank engine that generates new SEO pages, tracks rankings, and delivers monthly reports. Keeps your site climbing toward page one.",
    price: 149, price_label: "$149/mo", delivery_time: "Ongoing",
    features: ["AI-generated city-service pages (10–50/mo)", "Keyword research & targeting", "On-page SEO optimization", "JSON-LD structured data", "Automatic deployment", "Monthly ranking report", "Rank tracking dashboard"],
    deliverables: ["Monthly SEO pages", "Ranking report", "Keyword tracking"],
    seo_metadata: { meta_title: "Monthly SEO Rank & Report — Autonomous Page Generation", meta_description: "Autonomous rank engine that generates SEO pages, tracks rankings, and delivers monthly reports.", keywords: ["seo pages", "rank tracking", "city-service pages", "keyword research"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["SEO Rank & Report is a monthly service that autonomously generates 10-50 city-service pages, optimizes them for target keywords, deploys them automatically, and tracks rankings with a monthly report."], entity_types: ["Service"], topic_clusters: ["seo page generation", "rank tracking", "local seo"], llm_summary: "Monthly autonomous SEO page generation, ranking tracking, and reporting service." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "seo", "autonomous", "rank-engine"], related_services: ["monthly-citations", "monthly-backlinks", "monthly-gsc"], automation_function: "runRankEngine", pipeline_stage: "seo" },
    statistics: [{ label: "Pages/mo", value: "10–50" }, { label: "Avg. rank lift", value: "+15 positions" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-citations",
    name: "Citation Building",
    category: "monthly-service",
    tagline: "Monthly directory submissions to 50+ local citations",
    description: "Autonomous citation builder that submits your business to local directories every month, boosting local search visibility and building authority.",
    price: 99, price_label: "$99/mo", delivery_time: "Ongoing",
    features: ["50+ directory submissions/mo", "NAP consistency check", "Tier 1 & tier 2 directories", "Submission tracking", "Live link verification", "Monthly report"],
    deliverables: ["Citation submissions", "Live link report", "Monthly summary"],
    seo_metadata: { meta_title: "Monthly Citation Building — 50+ Local Directory Submissions", meta_description: "Autonomous citation builder that submits your business to 50+ local directories every month.", keywords: ["local citations", "directory submissions", "nap consistency", "local seo"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Citation Building is a monthly service that submits your business to 50+ local directories, checks NAP consistency, verifies live links, and delivers a monthly report."], entity_types: ["Service"], topic_clusters: ["local citations", "directory submissions", "local seo"], llm_summary: "Monthly autonomous local citation building across 50+ directories." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "seo", "citations", "autonomous"], related_services: ["monthly-seo-rank", "monthly-backlinks", "monthly-gbp"], automation_function: "autoBuildCitations", pipeline_stage: "seo" },
    statistics: [{ label: "Directories/mo", value: "50+" }, { label: "Avg. DA boost", value: "+8 points" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-backlinks",
    name: "Backlink Outreach",
    category: "monthly-service",
    tagline: "Monthly prospect discovery & personalized outreach",
    description: "Finds relevant backlink prospects, drafts personalized outreach emails, and tracks responses — every month, building authority at scale.",
    price: 149, price_label: "$149/mo", delivery_time: "Ongoing",
    features: ["50+ prospects discovered/mo", "Personalized email drafting", "Relevance & DA scoring", "Outreach tracking", "Follow-up automation", "Monthly report"],
    deliverables: ["Prospect list", "Outreach emails", "Monthly report"],
    seo_metadata: { meta_title: "Monthly Backlink Outreach — Prospect Discovery & Email Automation", meta_description: "Autonomous backlink outreach that finds prospects, drafts emails, and tracks responses every month.", keywords: ["backlinks", "outreach", "link building", "prospect discovery"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Backlink Outreach is a monthly service that discovers 50+ relevant prospects, drafts personalized emails, scores by DA, tracks responses, and sends automated follow-ups."], entity_types: ["Service"], topic_clusters: ["backlinks", "outreach", "link building"], llm_summary: "Monthly autonomous backlink prospect discovery, email outreach, and follow-up automation." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "seo", "backlinks", "autonomous"], related_services: ["monthly-seo-rank", "monthly-citations", "monthly-backlink-followup"], automation_function: "sendOutreach", pipeline_stage: "seo" },
    statistics: [{ label: "Prospects/mo", value: "50+" }, { label: "Response rate", value: "8–12%" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-content",
    name: "Content Generation",
    category: "monthly-service",
    tagline: "Monthly SEO-optimized articles & page refreshes",
    description: "Autonomous content engine that generates blog articles, service pages, and FAQ content tailored to your niche — and refreshes stale pages.",
    price: 99, price_label: "$99/mo", delivery_time: "Ongoing",
    features: ["10 articles/mo (1,200+ words each)", "SEO keyword integration", "Blog, service & FAQ formats", "Stale content refresh", "Industry-specific copy", "Monthly report"],
    deliverables: ["Monthly articles", "Content refresh", "Monthly report"],
    seo_metadata: { meta_title: "Monthly Content Generation — SEO Articles & Page Refreshes", meta_description: "Autonomous content engine that generates 10 SEO-optimized articles and refreshes stale pages every month.", keywords: ["content generation", "seo articles", "blog content", "faq content"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Content Generation is a monthly service that produces 10 SEO-optimized articles of 1,200+ words, refreshes stale content, and covers blog, service, and FAQ formats."], entity_types: ["Service"], topic_clusters: ["content generation", "seo content", "blog articles"], llm_summary: "Monthly autonomous SEO content generation — 10 articles, stale page refresh, industry-specific copy." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "content", "autonomous"], related_services: ["monthly-seo-rank", "monthly-content-distribution"], automation_function: "refreshStaleContent", pipeline_stage: "content" },
    statistics: [{ label: "Articles/mo", value: "10" }, { label: "Avg. word count", value: "1,200+" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-social",
    name: "Social Media Management",
    category: "monthly-service",
    tagline: "Monthly social posts with images across all platforms",
    description: "Autonomous social media generator that creates posts with images and captions across Facebook, Instagram, Twitter/X, and LinkedIn every month.",
    price: 149, price_label: "$149/mo", delivery_time: "Ongoing",
    features: ["30 social posts/mo (image + caption)", "Facebook, Instagram, Twitter/X, LinkedIn", "AI-generated post imagery", "Caption + hashtag suggestions", "Brand-matched colors", "Monthly report"],
    deliverables: ["Monthly social posts", "Post images", "Monthly report"],
    seo_metadata: { meta_title: "Monthly Social Media Management — 30 Posts Across 4 Platforms", meta_description: "Autonomous social media generator that creates 30 posts with images and captions across 4 platforms every month.", keywords: ["social media", "social posts", "instagram", "facebook", "linkedin"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Social Media Management is a monthly service that generates 30 social posts with AI images and captions across Facebook, Instagram, Twitter/X, and LinkedIn."], entity_types: ["Service"], topic_clusters: ["social media", "social posts", "content creation"], llm_summary: "Monthly autonomous social media post generation — 30 posts across 4 platforms with AI images and captions." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "social", "autonomous"], related_services: ["monthly-content", "monthly-content-distribution"], automation_function: "generateSocialMediaPack", pipeline_stage: "social" },
    statistics: [{ label: "Posts/mo", value: "30" }, { label: "Platforms", value: "4" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-gsc",
    name: "GSC Monitoring & Indexing",
    category: "monthly-service",
    tagline: "Monthly GSC sync, indexing requests & traffic tracking",
    description: "Autonomous GSC pipeline that syncs your properties, submits new pages for indexing, and tracks traffic — every month.",
    price: 99, price_label: "$99/mo", delivery_time: "Ongoing",
    features: ["GSC property sync", "Indexing requests for new pages", "Sitemap submission & monitoring", "Traffic & impression tracking", "Index coverage reports", "Monthly report"],
    deliverables: ["GSC sync", "Indexing report", "Monthly traffic report"],
    seo_metadata: { meta_title: "Monthly GSC Monitoring — Indexing & Traffic Tracking", meta_description: "Autonomous GSC pipeline that syncs properties, submits pages for indexing, and tracks traffic.", keywords: ["google search console", "gsc", "indexing", "sitemap", "traffic tracking"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["GSC Monitoring & Indexing is a monthly service that syncs Google Search Console properties, requests indexing for new pages, monitors sitemaps, and tracks traffic."], entity_types: ["Service"], topic_clusters: ["gsc", "indexing", "traffic tracking"], llm_summary: "Monthly autonomous Google Search Console sync, indexing requests, and traffic tracking." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "seo", "gsc", "autonomous"], related_services: ["monthly-seo-rank", "monthly-tech-seo"], automation_function: "submitToGSC", pipeline_stage: "seo" },
    statistics: [{ label: "Indexing requests", value: "Unlimited" }, { label: "Sync frequency", value: "Monthly" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-aeo",
    name: "AEO / AI Search Optimization",
    category: "monthly-service",
    tagline: "Monthly AI-search visibility optimization & monitoring",
    description: "Autonomous AEO engine that optimizes your content for AI search engines (ChatGPT, Perplexity, Google AI), monitors visibility, and builds answer blocks.",
    price: 149, price_label: "$149/mo", delivery_time: "Ongoing",
    features: ["AI-search answer block optimization", "AEO schema & topic modeling", "AI visibility monitoring", "Answer engine citation tracking", "Content optimization for LLMs", "Monthly AEO report"],
    deliverables: ["AEO optimization", "Visibility report", "Monthly summary"],
    seo_metadata: { meta_title: "Monthly AEO — AI Search Visibility Optimization", meta_description: "Autonomous AEO engine that optimizes content for AI search engines and monitors visibility.", keywords: ["aeo", "ai search", "answer optimization", "chatgpt", "perplexity"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["AEO / AI Search Optimization is a monthly service that optimizes content for AI search engines, builds answer blocks, monitors AI visibility, and tracks citation across ChatGPT, Perplexity, and Google AI."], entity_types: ["Service"], topic_clusters: ["aeo", "ai search", "answer optimization", "llm optimization"], llm_summary: "Monthly autonomous AI search engine optimization — answer blocks, schema, visibility monitoring, and citation tracking." },
    organizational_metadata: { tier: "elite", tags: ["monthly", "aeo", "ai-search", "autonomous"], related_services: ["monthly-seo-rank", "monthly-content"], automation_function: "optimizeAeo", pipeline_stage: "aeo" },
    statistics: [{ label: "AI engines tracked", value: "5+" }, { label: "Citation rate", value: "+25%" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-tech-seo",
    name: "Technical SEO Audits",
    category: "monthly-service",
    tagline: "Monthly technical SEO audits & fix recommendations",
    description: "Autonomous technical SEO auditor that crawls your site, identifies issues, and delivers prioritized fix recommendations every month.",
    price: 129, price_label: "$129/mo", delivery_time: "Ongoing",
    features: ["Full technical SEO crawl", "Core Web Vitals monitoring", "Schema validation", "Mobile-friendliness check", "Prioritized fix recommendations", "Monthly audit report"],
    deliverables: ["Audit report", "Fix recommendations", "Monthly summary"],
    seo_metadata: { meta_title: "Monthly Technical SEO Audits — Crawl, Core Web Vitals & Fixes", meta_description: "Autonomous technical SEO auditor that crawls your site and delivers fix recommendations monthly.", keywords: ["technical seo", "core web vitals", "schema validation", "seo audit"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Technical SEO Audits is a monthly service that crawls your site for technical issues, monitors Core Web Vitals, validates schema, checks mobile-friendliness, and delivers prioritized fix recommendations."], entity_types: ["Service"], topic_clusters: ["technical seo", "core web vitals", "schema validation"], llm_summary: "Monthly autonomous technical SEO audit — crawl, Core Web Vitals, schema validation, and prioritized fixes." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "seo", "technical", "autonomous"], related_services: ["monthly-seo-rank", "monthly-gsc"], automation_function: "runTechnicalSeoAudit", pipeline_stage: "seo" },
    statistics: [{ label: "Checks/mo", value: "50+" }, { label: "Issues found", value: "Tracked" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-competitor-intel",
    name: "Competitor Intelligence",
    category: "monthly-service",
    tagline: "Monthly competitor analysis & gap exploitation",
    description: "Autonomous competitor analysis that identifies competitor strategies, content gaps, and ranking opportunities to exploit every month.",
    price: 129, price_label: "$129/mo", delivery_time: "Ongoing",
    features: ["Competitor website analysis", "Content gap identification", "Keyword opportunity reports", "SERP weakness scoring", "Backlink gap analysis", "Monthly intelligence report"],
    deliverables: ["Competitor report", "Gap analysis", "Monthly intelligence"],
    seo_metadata: { meta_title: "Monthly Competitor Intelligence — Gap Analysis & SERP Scoring", meta_description: "Autonomous competitor analysis that identifies strategies, content gaps, and ranking opportunities monthly.", keywords: ["competitor analysis", "content gaps", "serp analysis", "backlink gaps"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Competitor Intelligence is a monthly service that analyzes competitor websites, identifies content and keyword gaps, scores SERP weakness, and analyzes backlink gaps."], entity_types: ["Service"], topic_clusters: ["competitor analysis", "gap analysis", "serp analysis"], llm_summary: "Monthly autonomous competitor intelligence — website analysis, content gaps, SERP weakness, and backlink gaps." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "seo", "competitor", "autonomous"], related_services: ["monthly-seo-rank", "monthly-backlinks"], automation_function: "analyzeCompetitorGaps", pipeline_stage: "seo" },
    statistics: [{ label: "Competitors tracked", value: "10+" }, { label: "Gaps found/mo", value: "5–15" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-gbp",
    name: "Google Business Profile Management",
    category: "monthly-service",
    tagline: "Monthly GBP posts, updates & optimization",
    description: "Autonomous GBP manager that posts updates, optimizes categories, responds to reviews, and tracks local pack visibility.",
    price: 99, price_label: "$99/mo", delivery_time: "Ongoing",
    features: ["Monthly GBP posts", "Category & service area optimization", "Review response management", "Photo uploads & optimization", "Q&A monitoring & responses", "Monthly local pack report"],
    deliverables: ["GBP posts", "Optimization report", "Monthly summary"],
    seo_metadata: { meta_title: "Monthly Google Business Profile Management — Posts & Optimization", meta_description: "Autonomous GBP manager that posts updates, optimizes categories, and responds to reviews monthly.", keywords: ["google business profile", "gbp", "local pack", "review management"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Google Business Profile Management is a monthly service that posts GBP updates, optimizes categories, responds to reviews, uploads photos, monitors Q&A, and tracks local pack visibility."], entity_types: ["Service"], topic_clusters: ["gbp", "local seo", "review management", "local pack"], llm_summary: "Monthly autonomous Google Business Profile management — posts, optimization, review responses, and local pack tracking." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "seo", "gbp", "autonomous", "local"], related_services: ["monthly-citations", "monthly-reviews"], automation_function: "autoOptimizeSites", pipeline_stage: "seo" },
    statistics: [{ label: "Local pack visibility", value: "+60%" }, { label: "Posts/mo", value: "4+" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-reviews",
    name: "Review Management",
    category: "monthly-service",
    tagline: "Automated review requests & reputation monitoring",
    description: "Automated review request system that sends review links to your customers, tracks reviews, and alerts you to negative feedback.",
    price: 79, price_label: "$79/mo", delivery_time: "Ongoing",
    features: ["Automated review requests", "SMS + email delivery", "Review tracking dashboard", "Negative review alerts", "Response templates", "Monthly report"],
    deliverables: ["Review system", "Tracking dashboard", "Monthly report"],
    seo_metadata: { meta_title: "Monthly Review Management — Automated Requests & Reputation Monitoring", meta_description: "Automated review request system with reputation monitoring and negative review alerts.", keywords: ["review management", "review requests", "reputation", "google reviews"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Review Management is a monthly service that sends automated review requests via SMS and email, tracks reviews, alerts you to negative feedback, and provides response templates."], entity_types: ["Service"], topic_clusters: ["review management", "reputation", "reviews"], llm_summary: "Monthly automated review request system with reputation monitoring and negative review alerts." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "reputation", "reviews", "autonomous"], related_services: ["monthly-gbp", "monthly-citations"], automation_function: "autoOptimizeSites", pipeline_stage: "seo" },
    statistics: [{ label: "Review rate", value: "+35%" }, { label: "Alerts", value: "Real-time" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-site-maintenance",
    name: "Website Maintenance",
    category: "monthly-service",
    tagline: "Monthly site updates, security & performance monitoring",
    description: "Autonomous site maintenance that keeps your website updated, secure, and fast — with monthly performance reports.",
    price: 99, price_label: "$99/mo", delivery_time: "Ongoing",
    features: ["Security monitoring & patches", "Performance optimization", "Content updates & refreshes", "Uptime monitoring", "Backup verification", "Monthly maintenance report"],
    deliverables: ["Maintenance report", "Security scan", "Monthly summary"],
    seo_metadata: { meta_title: "Monthly Website Maintenance — Security, Performance & Uptime", meta_description: "Autonomous site maintenance that keeps your website updated, secure, and fast.", keywords: ["website maintenance", "security monitoring", "performance optimization", "uptime"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Website Maintenance is a monthly service that monitors security, optimizes performance, updates content, monitors uptime, verifies backups, and delivers a monthly maintenance report."], entity_types: ["Service"], topic_clusters: ["website maintenance", "security", "performance", "uptime"], llm_summary: "Monthly autonomous website maintenance — security, performance, content updates, uptime monitoring, and backup verification." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "maintenance", "security", "autonomous"], related_services: ["monthly-tech-seo"], automation_function: "runSeoMaintenance", pipeline_stage: "maintenance" },
    statistics: [{ label: "Uptime", value: "99.9%" }, { label: "Response time", value: "<2s" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-lead-gen",
    name: "Lead Generation Pipeline",
    category: "monthly-service",
    tagline: "Monthly lead discovery, scoring & nurturing",
    description: "Autonomous lead generation engine that discovers high-value prospects, scores them, and nurtures them through the pipeline every month.",
    price: 199, price_label: "$199/mo", delivery_time: "Ongoing",
    features: ["High-value prospect discovery", "Lead scoring & qualification", "Nurture sequence automation", "CRM pipeline sync", "Lead source attribution", "Monthly lead report"],
    deliverables: ["Prospect list", "Lead report", "Monthly summary"],
    seo_metadata: { meta_title: "Monthly Lead Generation — Prospect Discovery & Nurturing", meta_description: "Autonomous lead generation engine that discovers, scores, and nurtures prospects monthly.", keywords: ["lead generation", "prospect discovery", "lead scoring", "nurture sequences"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Lead Generation Pipeline is a monthly service that discovers high-value prospects, scores and qualifies them, automates nurture sequences, syncs to CRM, and attributes lead sources."], entity_types: ["Service"], topic_clusters: ["lead generation", "prospect discovery", "lead nurturing"], llm_summary: "Monthly autonomous lead generation — prospect discovery, scoring, nurture automation, and CRM sync." },
    organizational_metadata: { tier: "elite", tags: ["monthly", "lead-gen", "autonomous", "pipeline"], related_services: ["monthly-seo-rank", "monthly-chatbot"], automation_function: "discoverHighValueDomains", pipeline_stage: "lead-gen" },
    statistics: [{ label: "Prospects/mo", value: "100+" }, { label: "Qualified leads", value: "20–40" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-rank-alerts",
    name: "Rank Alert Monitoring",
    category: "monthly-service",
    tagline: "Real-time rank drop alerts & recovery recommendations",
    description: "Autonomous rank monitor that watches your keyword positions, alerts you to drops, and recommends recovery actions.",
    price: 69, price_label: "$69/mo", delivery_time: "Ongoing",
    features: ["Daily rank position tracking", "Real-time drop alerts", "Recovery recommendations", "Competitor position monitoring", "SERP feature tracking", "Monthly alert summary"],
    deliverables: ["Rank alerts", "Recovery recommendations", "Monthly summary"],
    seo_metadata: { meta_title: "Monthly Rank Alert Monitoring — Drop Alerts & Recovery", meta_description: "Autonomous rank monitor that watches positions, alerts you to drops, and recommends recovery.", keywords: ["rank tracking", "rank alerts", "rank drop", "serp tracking"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Rank Alert Monitoring is a monthly service that tracks keyword positions daily, sends real-time drop alerts, recommends recovery actions, monitors competitors, and tracks SERP features."], entity_types: ["Service"], topic_clusters: ["rank tracking", "rank alerts", "serp monitoring"], llm_summary: "Monthly autonomous rank monitoring — daily tracking, real-time drop alerts, and recovery recommendations." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "seo", "rank-tracking", "autonomous", "alerts"], related_services: ["monthly-seo-rank", "monthly-tech-seo"], automation_function: "checkRankAlerts", pipeline_stage: "seo" },
    statistics: [{ label: "Keywords tracked", value: "Unlimited" }, { label: "Alert speed", value: "Real-time" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-content-distribution",
    name: "Content Distribution",
    category: "monthly-service",
    tagline: "Monthly content syndication across web & social channels",
    description: "Autonomous content distribution engine that syndicates your content across web channels, social platforms, and content networks.",
    price: 99, price_label: "$99/mo", delivery_time: "Ongoing",
    features: ["Multi-channel content syndication", "Social media cross-posting", "Content network distribution", "IndexNow submission", "RSS & feed management", "Monthly distribution report"],
    deliverables: ["Distribution report", "Syndication log", "Monthly summary"],
    seo_metadata: { meta_title: "Monthly Content Distribution — Multi-Channel Syndication", meta_description: "Autonomous content distribution engine that syndicates content across web and social channels.", keywords: ["content distribution", "syndication", "cross-posting", "indexnow"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Content Distribution is a monthly service that syndicates content across multiple channels, cross-posts to social media, distributes through content networks, submits to IndexNow, and manages RSS feeds."], entity_types: ["Service"], topic_clusters: ["content distribution", "syndication", "content marketing"], llm_summary: "Monthly autonomous content distribution — multi-channel syndication, social cross-posting, and IndexNow submission." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "content", "distribution", "autonomous"], related_services: ["monthly-content", "monthly-social"], automation_function: "automateContentDistribution", pipeline_stage: "content" },
    statistics: [{ label: "Channels", value: "10+" }, { label: "Posts distributed/mo", value: "50+" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-backlink-followup",
    name: "Backlink Follow-up Sequence",
    category: "monthly-service",
    tagline: "Automated follow-up sequences for outreach prospects",
    description: "Autonomous follow-up engine that sends sequenced follow-up emails to backlink prospects, maximizing response rates.",
    price: 79, price_label: "$79/mo", delivery_time: "Ongoing",
    features: ["Automated follow-up sequences", "Personalized follow-up emails", "Response tracking", "Reply rate optimization", "Sequence scheduling", "Monthly follow-up report"],
    deliverables: ["Follow-up sequences", "Response tracking", "Monthly report"],
    seo_metadata: { meta_title: "Monthly Backlink Follow-up — Automated Outreach Sequences", meta_description: "Autonomous follow-up engine that sends sequenced emails to backlink prospects.", keywords: ["backlink follow-up", "outreach sequences", "reply rate", "link building"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Backlink Follow-up Sequence is a monthly service that sends automated, personalized follow-up emails to backlink prospects, tracks responses, and optimizes reply rates."], entity_types: ["Service"], topic_clusters: ["backlink outreach", "follow-up sequences", "link building"], llm_summary: "Monthly autonomous backlink follow-up — sequenced emails, response tracking, and reply rate optimization." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "seo", "backlinks", "outreach", "autonomous"], related_services: ["monthly-backlinks"], automation_function: "sendFollowUp", pipeline_stage: "seo" },
    statistics: [{ label: "Follow-up rate", value: "+45%" }, { label: "Sequences/mo", value: "Unlimited" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-call-tracking",
    name: "Call Tracking & Analytics",
    category: "monthly-service",
    tagline: "Dedicated tracking number with call recording & analytics",
    description: "Dedicated tracking phone number with call recording, analytics, and lead source attribution — billed monthly.",
    price: 79, price_label: "$79/mo", delivery_time: "Ongoing",
    features: ["Dedicated tracking number", "Call recording", "Call analytics dashboard", "Lead source attribution", "SMS notifications", "Monthly analytics report"],
    deliverables: ["Tracking number", "Analytics dashboard", "Monthly report"],
    seo_metadata: { meta_title: "Monthly Call Tracking — Recording, Analytics & Attribution", meta_description: "Dedicated tracking phone number with call recording, analytics, and lead source attribution.", keywords: ["call tracking", "call recording", "lead attribution", "analytics"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["Call Tracking & Analytics is a monthly service that provides a dedicated tracking number with call recording, an analytics dashboard, lead source attribution, and SMS notifications."], entity_types: ["Service"], topic_clusters: ["call tracking", "call analytics", "lead attribution"], llm_summary: "Monthly call tracking — dedicated number, recording, analytics dashboard, and lead source attribution." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "analytics", "call-tracking"], related_services: ["monthly-lead-gen"], automation_function: "", pipeline_stage: "analytics" },
    statistics: [{ label: "Call tracking", value: "100%" }, { label: "Recording", value: "Included" }, { label: "Report", value: "Monthly" }],
  },
  {
    product_id: "monthly-chatbot",
    name: "AI Chatbot Management",
    category: "monthly-service",
    tagline: "24/7 AI chatbot optimization & lead routing",
    description: "Monthly chatbot management — lead qualification optimization, FAQ updates, appointment booking, and CRM integration.",
    price: 99, price_label: "$99/mo", delivery_time: "Ongoing",
    features: ["AI-powered lead qualification", "Appointment booking", "FAQ answering & updates", "Lead capture & routing", "CRM integration", "Monthly optimization report"],
    deliverables: ["Chatbot config", "Lead routing", "Monthly report"],
    seo_metadata: { meta_title: "Monthly AI Chatbot Management — Lead Qualification & Routing", meta_description: "Monthly chatbot management with lead qualification, FAQ updates, and CRM integration.", keywords: ["ai chatbot", "lead qualification", "appointment booking", "crm integration"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["AI Chatbot Management is a monthly service that optimizes lead qualification, manages appointment booking, updates FAQs, routes leads, integrates with CRM, and delivers a monthly optimization report."], entity_types: ["Service"], topic_clusters: ["ai chatbot", "lead qualification", "crm"], llm_summary: "Monthly AI chatbot management — lead qualification, FAQ updates, appointment booking, and CRM integration." },
    organizational_metadata: { tier: "pro", tags: ["monthly", "chatbot", "ai", "autonomous"], related_services: ["monthly-lead-gen"], automation_function: "", pipeline_stage: "conversion" },
    statistics: [{ label: "Lead capture rate", value: "+40%" }, { label: "Availability", value: "24/7" }, { label: "Report", value: "Monthly" }],
  },

  // ─── FREE PRODUCTS ───────────────────────────────────────
  {
    product_id: "free-seo-audit",
    name: "Free SEO Audit",
    category: "free",
    tagline: "Instant technical & content SEO audit — no cost",
    description: "Get a free SEO audit of your website — technical issues, content gaps, and quick-win opportunities. No signup required.",
    price: 0, price_label: "Free", delivery_time: "Instant",
    features: ["Technical SEO scan", "Content gap analysis", "Keyword opportunity report", "Quick-win recommendations", "Instant results", "No credit card required"],
    deliverables: ["SEO audit report", "Quick-win list"],
    seo_metadata: { meta_title: "Free SEO Audit — Instant Technical & Content Analysis", meta_description: "Get a free SEO audit of your website — technical issues, content gaps, and quick-win opportunities.", keywords: ["free seo audit", "seo scan", "content gaps", "quick wins"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["The Free SEO Audit provides an instant technical and content SEO scan of your website, identifying technical issues, content gaps, keyword opportunities, and quick-win recommendations at no cost."], entity_types: ["Service"], topic_clusters: ["seo audit", "free tools", "technical seo"], llm_summary: "Free instant SEO audit — technical scan, content gaps, keyword opportunities, and quick-win recommendations." },
    organizational_metadata: { tier: "free", tags: ["free", "seo", "audit", "lead-magnet"], related_services: ["monthly-seo-rank", "monthly-tech-seo"], automation_function: "run-free-audit", pipeline_stage: "audit" },
    statistics: [{ label: "Checks", value: "50+" }, { label: "Delivery", value: "Instant" }, { label: "Cost", value: "Free" }],
  },
  {
    product_id: "free-business-names",
    name: "Free Business Name Generator",
    category: "free",
    tagline: "AI-powered business name ideas with domain check — free",
    description: "Generate creative business name ideas with viral potential scoring, domain availability check, and trademark screening — completely free.",
    price: 0, price_label: "Free", delivery_time: "Instant",
    features: ["20 AI-generated name ideas", "Viral potential scoring", "Domain availability check", "Trademark screening", "State registry check", "Google uniqueness check"],
    deliverables: ["Name ideas", "Domain check results"],
    seo_metadata: { meta_title: "Free Business Name Generator — AI Ideas with Domain Check", meta_description: "Generate creative business name ideas with viral potential scoring and domain availability check — free.", keywords: ["business name generator", "domain check", "trademark screening", "free tools"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["The Free Business Name Generator creates 20 AI-powered business name ideas with viral potential scoring, domain availability check, trademark screening, state registry check, and Google uniqueness verification."], entity_types: ["Service"], topic_clusters: ["business names", "domain check", "free tools"], llm_summary: "Free AI business name generator — 20 ideas with viral scoring, domain check, and trademark screening." },
    organizational_metadata: { tier: "free", tags: ["free", "branding", "naming", "lead-magnet"], related_services: ["free-domain-check", "free-logo-concept"], automation_function: "recommendBusinessNames", pipeline_stage: "branding" },
    statistics: [{ label: "Names generated", value: "20" }, { label: "Delivery", value: "Instant" }, { label: "Cost", value: "Free" }],
  },
  {
    product_id: "free-domain-check",
    name: "Free Domain Availability Check",
    category: "free",
    tagline: "Check any domain's availability instantly — free",
    description: "Check domain availability with RDAP lookup, pricing, and purchase links. No cost, no signup.",
    price: 0, price_label: "Free", delivery_time: "Instant",
    features: ["Instant RDAP availability check", "Domain pricing lookup", "Registrar purchase link", "Bulk domain check", "TLD suggestions", "No signup required"],
    deliverables: ["Domain availability report"],
    seo_metadata: { meta_title: "Free Domain Availability Check — Instant RDAP Lookup", meta_description: "Check domain availability with RDAP lookup, pricing, and purchase links. No cost, no signup.", keywords: ["domain check", "rdap", "domain availability", "free tools"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["The Free Domain Availability Check provides instant RDAP lookup for any domain, with pricing, registrar purchase links, bulk checking, and TLD suggestions at no cost."], entity_types: ["Service"], topic_clusters: ["domain check", "rdap", "free tools"], llm_summary: "Free instant domain availability check — RDAP lookup, pricing, and purchase links." },
    organizational_metadata: { tier: "free", tags: ["free", "domain", "lead-magnet"], related_services: ["free-business-names"], automation_function: "checkDomainAvailability", pipeline_stage: "domain" },
    statistics: [{ label: "Check speed", value: "Instant" }, { label: "TLDs supported", value: "All" }, { label: "Cost", value: "Free" }],
  },
  {
    product_id: "free-logo-concept",
    name: "Free Logo Concept",
    category: "free",
    tagline: "1 free AI logo concept — no credit card",
    description: "Try our AI logo generator with 1 free concept. See the quality before you buy the full 10-concept pack.",
    price: 0, price_label: "Free", delivery_time: "Instant",
    features: ["1 AI-generated logo concept", "PNG download", "Your business name & industry", "Color variation", "No watermark", "No credit card required"],
    deliverables: ["1 logo concept (PNG)"],
    seo_metadata: { meta_title: "Free AI Logo Concept — No Credit Card Required", meta_description: "Try our AI logo generator with 1 free concept. No watermark, no credit card.", keywords: ["free logo", "ai logo", "logo concept", "free tools"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["The Free Logo Concept provides 1 AI-generated logo concept from your business name and industry, with a PNG download, color variation, no watermark, and no credit card required."], entity_types: ["Service"], topic_clusters: ["logo design", "free tools", "ai logo"], llm_summary: "Free AI logo concept — 1 design with PNG download, no watermark, no credit card." },
    organizational_metadata: { tier: "free", tags: ["free", "branding", "logo", "lead-magnet"], related_services: ["ai-tool-logo", "free-business-names"], automation_function: "", pipeline_stage: "branding" },
    statistics: [{ label: "Concepts", value: "1" }, { label: "Delivery", value: "Instant" }, { label: "Cost", value: "Free" }],
  },
  {
    product_id: "free-competitor-scan",
    name: "Free Competitor Scan",
    category: "free",
    tagline: "Basic competitor analysis — see who's ranking & why",
    description: "Get a free basic competitor scan — see who's ranking for your keywords, their content gaps, and quick opportunities.",
    price: 0, price_label: "Free", delivery_time: "Instant",
    features: ["Top 10 competitor identification", "Content gap summary", "Keyword overlap report", "Quick-win opportunities", "Basic SERP analysis", "No credit card required"],
    deliverables: ["Competitor scan report"],
    seo_metadata: { meta_title: "Free Competitor Scan — See Who's Ranking & Why", meta_description: "Get a free basic competitor scan — see who's ranking for your keywords and their content gaps.", keywords: ["competitor scan", "competitor analysis", "serp analysis", "free tools"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["The Free Competitor Scan identifies the top 10 competitors for your keywords, summarizes content gaps, reports keyword overlap, identifies quick-win opportunities, and provides basic SERP analysis."], entity_types: ["Service"], topic_clusters: ["competitor analysis", "serp analysis", "free tools"], llm_summary: "Free competitor scan — top 10 competitors, content gaps, keyword overlap, and quick-win opportunities." },
    organizational_metadata: { tier: "free", tags: ["free", "seo", "competitor", "lead-magnet"], related_services: ["monthly-competitor-intel"], automation_function: "analyzeCompetitorGaps", pipeline_stage: "audit" },
    statistics: [{ label: "Competitors scanned", value: "10" }, { label: "Delivery", value: "Instant" }, { label: "Cost", value: "Free" }],
  },
  {
    product_id: "free-gbp-check",
    name: "Free GBP Health Check",
    category: "free",
    tagline: "Audit your Google Business Profile — free",
    description: "Get a free health check of your Google Business Profile — find optimization gaps and local pack opportunities.",
    price: 0, price_label: "Free", delivery_time: "Instant",
    features: ["GBP completeness audit", "Category optimization check", "Photo & review analysis", "Local pack opportunity scan", "Quick-fix recommendations", "No credit card required"],
    deliverables: ["GBP health report"],
    seo_metadata: { meta_title: "Free Google Business Profile Health Check", meta_description: "Get a free health check of your Google Business Profile — find optimization gaps and local pack opportunities.", keywords: ["gbp check", "google business profile", "local pack", "free tools"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["The Free GBP Health Check audits your Google Business Profile for completeness, category optimization, photo and review quality, local pack opportunities, and provides quick-fix recommendations."], entity_types: ["Service"], topic_clusters: ["gbp", "local seo", "free tools"], llm_summary: "Free Google Business Profile health check — completeness audit, category optimization, and local pack opportunities." },
    organizational_metadata: { tier: "free", tags: ["free", "seo", "gbp", "lead-magnet"], related_services: ["monthly-gbp"], automation_function: "", pipeline_stage: "audit" },
    statistics: [{ label: "Checks", value: "25+" }, { label: "Delivery", value: "Instant" }, { label: "Cost", value: "Free" }],
  },
  {
    product_id: "free-keyword-research",
    name: "Free Keyword Research",
    category: "free",
    tagline: "Basic keyword research report for your niche — free",
    description: "Get a free keyword research report — search volume, CPC, and ranking difficulty for your industry.",
    price: 0, price_label: "Free", delivery_time: "Instant",
    features: ["20 target keywords", "Search volume estimates", "CPC & lead value data", "Ranking difficulty scores", "Keyword opportunity map", "No credit card required"],
    deliverables: ["Keyword research report"],
    seo_metadata: { meta_title: "Free Keyword Research — 20 Keywords with Volume & Difficulty", meta_description: "Get a free keyword research report — search volume, CPC, and ranking difficulty for your industry.", keywords: ["keyword research", "search volume", "cpc", "free tools"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["The Free Keyword Research report provides 20 target keywords for your niche with search volume estimates, CPC and lead value data, ranking difficulty scores, and a keyword opportunity map."], entity_types: ["Service"], topic_clusters: ["keyword research", "free tools", "seo"], llm_summary: "Free keyword research — 20 target keywords with search volume, CPC, and difficulty scores." },
    organizational_metadata: { tier: "free", tags: ["free", "seo", "keywords", "lead-magnet"], related_services: ["monthly-seo-rank"], automation_function: "", pipeline_stage: "audit" },
    statistics: [{ label: "Keywords", value: "20" }, { label: "Delivery", value: "Instant" }, { label: "Cost", value: "Free" }],
  },
  {
    product_id: "free-speed-test",
    name: "Free Website Speed Test",
    category: "free",
    tagline: "Test your website speed & performance — free",
    description: "Get a free website speed test — Core Web Vitals, load time, and performance recommendations.",
    price: 0, price_label: "Free", delivery_time: "Instant",
    features: ["Core Web Vitals report", "Page load time analysis", "Performance score", "Optimization recommendations", "Mobile & desktop test", "No credit card required"],
    deliverables: ["Speed test report"],
    seo_metadata: { meta_title: "Free Website Speed Test — Core Web Vitals & Performance", meta_description: "Get a free website speed test — Core Web Vitals, load time, and performance recommendations.", keywords: ["speed test", "core web vitals", "performance", "free tools"], schema_type: "Service" },
    aeo_metadata: { answer_blocks: ["The Free Website Speed Test provides a Core Web Vitals report, page load time analysis, overall performance score, and optimization recommendations for both mobile and desktop."], entity_types: ["Service"], topic_clusters: ["speed test", "core web vitals", "performance", "free tools"], llm_summary: "Free website speed test — Core Web Vitals, load time, performance score, and optimization recommendations." },
    organizational_metadata: { tier: "free", tags: ["free", "seo", "performance", "lead-magnet"], related_services: ["monthly-tech-seo"], automation_function: "", pipeline_stage: "audit" },
    statistics: [{ label: "Metrics", value: "10+" }, { label: "Delivery", value: "Instant" }, { label: "Cost", value: "Free" }],
  },
];